// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/v1/commit_response.proto

package com.google.spanner.v1;

public interface CommitResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.spanner.v1.CommitResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The Cloud Spanner timestamp at which the transaction committed.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp commit_timestamp = 1;</code>
   * @return Whether the commitTimestamp field is set.
   */
  boolean hasCommitTimestamp();
  /**
   * <pre>
   * The Cloud Spanner timestamp at which the transaction committed.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp commit_timestamp = 1;</code>
   * @return The commitTimestamp.
   */
  com.google.protobuf.Timestamp getCommitTimestamp();
  /**
   * <pre>
   * The Cloud Spanner timestamp at which the transaction committed.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp commit_timestamp = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCommitTimestampOrBuilder();

  /**
   * <pre>
   * The statistics about this Commit. Not returned by default.
   * For more information, see
   * [CommitRequest.return_commit_stats][google.spanner.v1.CommitRequest.return_commit_stats].
   * </pre>
   *
   * <code>.google.spanner.v1.CommitResponse.CommitStats commit_stats = 2;</code>
   * @return Whether the commitStats field is set.
   */
  boolean hasCommitStats();
  /**
   * <pre>
   * The statistics about this Commit. Not returned by default.
   * For more information, see
   * [CommitRequest.return_commit_stats][google.spanner.v1.CommitRequest.return_commit_stats].
   * </pre>
   *
   * <code>.google.spanner.v1.CommitResponse.CommitStats commit_stats = 2;</code>
   * @return The commitStats.
   */
  com.google.spanner.v1.CommitResponse.CommitStats getCommitStats();
  /**
   * <pre>
   * The statistics about this Commit. Not returned by default.
   * For more information, see
   * [CommitRequest.return_commit_stats][google.spanner.v1.CommitRequest.return_commit_stats].
   * </pre>
   *
   * <code>.google.spanner.v1.CommitResponse.CommitStats commit_stats = 2;</code>
   */
  com.google.spanner.v1.CommitResponse.CommitStatsOrBuilder getCommitStatsOrBuilder();
}
