// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/executor/v1/cloud_executor.proto

// Protobuf Java Version: 3.25.2
package com.google.spanner.executor.v1;

public interface TransactionExecutionOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.spanner.executor.v1.TransactionExecutionOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether optimistic concurrency should be used to execute this transaction.
   * </pre>
   *
   * <code>bool optimistic = 1;</code>
   * @return The optimistic.
   */
  boolean getOptimistic();
}
