# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

docker:
  image: "gcr.io/cloud-devrel-public-resources/owlbot-java:latest"

deep-remove-regex:
- "/grpc-google-.*/src"
- "/proto-google-.*/src"
- "/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1"
- "/google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin"

deep-preserve-regex:
- "/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java"
- "/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CryptoKeyName.java"
- "/proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CryptoKeyVersionName.java"

deep-copy-regex:
- source: "/google/spanner/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/$1/proto-google-cloud-spanner-$1/src"
- source: "/google/spanner/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/$1/grpc-google-cloud-spanner-$1/src"
- source: "/google/spanner/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/$1/google-cloud-spanner/src/"
- source: "/google/spanner/admin/database/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/$1/proto-google-cloud-spanner-admin-database-$1/src"
- source: "/google/spanner/admin/database/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/$1/grpc-google-cloud-spanner-admin-database-$1/src"
- source: "/google/spanner/admin/database/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/$1/google-cloud-spanner/src/"
- source: "/google/spanner/admin/instance/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/$1/proto-google-cloud-spanner-admin-instance-$1/src"
- source: "/google/spanner/admin/instance/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/$1/grpc-google-cloud-spanner-admin-instance-$1/src"
- source: "/google/spanner/admin/instance/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/$1/google-cloud-spanner/src/"
- source: "/google/spanner/executor/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/$1/proto-google-cloud-spanner-executor-$1/src"
- source: "/google/spanner/executor/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/$1/grpc-google-cloud-spanner-executor-$1/src"
- source: "/google/spanner/executor/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/$1/google-cloud-spanner-executor/src/"
