releaseType: java-yoshi
bumpMinorPreMajor: true
handleGHRelease: true
branches:
  - branch: 3.3.x
    releaseType: java-yoshi
    bumpMinorPreMajor: true
    handleGHRelease: true
  - branch: 4.0.x
    releaseType: java-yoshi
    bumpMinorPreMajor: true
    handleGHRelease: true
  - branch: 5.2.x
    releaseType: java-yoshi
    bumpMinorPreMajor: true
    handleGHRelease: true
  - releaseType: java-lts
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 6.4.4-sp
  - releaseType: java-backport
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 6.14.x
  - releaseType: java-yoshi
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 6.23.x
  - releaseType: java-yoshi
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 6.33.x
  - releaseType: java-backport
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 6.55.x
  - releaseType: java-backport
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 6.67.x
  - releaseType: java-backport
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 6.66.x
