releaseType: java-yoshi
bumpMinorPreMajor: true
handleGHRelease: true
branches:
    - branch: 3.3.x
    - branch: 4.0.x
    - branch: 5.2.x
    - releaseType: java-lts
      branch: 6.4.4-sp
    - releaseType: java-backport
      branch: 6.14.x
    - branch: 6.23.x
    - branch: 6.33.x
    - releaseType: java-backport
      branch: 6.55.x
    - releaseType: java-backport
      branch: 6.67.x
    - releaseType: java-backport
      branch: 6.66.x
    - releaseType: java-backport
      branch: 6.88.x
    - releaseType: java-backport
      branch: 6.96.x
    - releaseType: java-backport
      branch: 6.95.x
    - branch: protobuf-4.x-rc
      manifest: true
