apiVersion: batch/v1
kind: Job
metadata:
  name: bypass-point-read-test
  namespace: spanner-ns
spec:
  template:
    spec:
      containers:
      - name: test-runner
        image: us-west1-docker.pkg.dev/outbound-flight/spanner-box/irahul-client:cloudtop
        imagePullPolicy: Always
        env:
        - name: BYPASS_HOST
          value: "http://spanner-a-1.pod.spanner-ns:15000"
      restartPolicy: Never
  backoffLimit: 1
