// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spanner/admin/database/v1/backup.proto
// Protobuf Java Version: 4.33.0

package com.google.spanner.admin.database.v1;

@com.google.protobuf.Generated
public interface BackupInstancePartitionOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.spanner.admin.database.v1.BackupInstancePartition)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * A unique identifier for the instance partition. Values are of the form
   * `projects/&lt;project&gt;/instances/&lt;instance&gt;/instancePartitions/&lt;instance_partition_id&gt;`
   * </pre>
   *
   * <code>string instance_partition = 1 [(.google.api.resource_reference) = { ... }</code>
   *
   * @return The instancePartition.
   */
  java.lang.String getInstancePartition();

  /**
   *
   *
   * <pre>
   * A unique identifier for the instance partition. Values are of the form
   * `projects/&lt;project&gt;/instances/&lt;instance&gt;/instancePartitions/&lt;instance_partition_id&gt;`
   * </pre>
   *
   * <code>string instance_partition = 1 [(.google.api.resource_reference) = { ... }</code>
   *
   * @return The bytes for instancePartition.
   */
  com.google.protobuf.ByteString getInstancePartitionBytes();
}
