// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spanner/admin/database/v1/spanner_database_admin.proto
// Protobuf Java Version: 4.33.0

package com.google.spanner.admin.database.v1;

@com.google.protobuf.Generated
public interface RestoreInfoOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.spanner.admin.database.v1.RestoreInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The type of the restore source.
   * </pre>
   *
   * <code>.google.spanner.admin.database.v1.RestoreSourceType source_type = 1;</code>
   *
   * @return The enum numeric value on the wire for sourceType.
   */
  int getSourceTypeValue();

  /**
   *
   *
   * <pre>
   * The type of the restore source.
   * </pre>
   *
   * <code>.google.spanner.admin.database.v1.RestoreSourceType source_type = 1;</code>
   *
   * @return The sourceType.
   */
  com.google.spanner.admin.database.v1.RestoreSourceType getSourceType();

  /**
   *
   *
   * <pre>
   * Information about the backup used to restore the database. The backup
   * may no longer exist.
   * </pre>
   *
   * <code>.google.spanner.admin.database.v1.BackupInfo backup_info = 2;</code>
   *
   * @return Whether the backupInfo field is set.
   */
  boolean hasBackupInfo();

  /**
   *
   *
   * <pre>
   * Information about the backup used to restore the database. The backup
   * may no longer exist.
   * </pre>
   *
   * <code>.google.spanner.admin.database.v1.BackupInfo backup_info = 2;</code>
   *
   * @return The backupInfo.
   */
  com.google.spanner.admin.database.v1.BackupInfo getBackupInfo();

  /**
   *
   *
   * <pre>
   * Information about the backup used to restore the database. The backup
   * may no longer exist.
   * </pre>
   *
   * <code>.google.spanner.admin.database.v1.BackupInfo backup_info = 2;</code>
   */
  com.google.spanner.admin.database.v1.BackupInfoOrBuilder getBackupInfoOrBuilder();

  com.google.spanner.admin.database.v1.RestoreInfo.SourceInfoCase getSourceInfoCase();
}
