// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package com.example.spanner.protobuf.book;

public final class BookProto {
  private BookProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_book_Book_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_book_Book_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
        "\n\nbook.proto\022\010com.book\"S\n\004Book\022\014\n\004isbn\030\001" +
            " \001(\003\022\r\n\005title\030\002 \001(\t\022\016\n\006author\030\003 \001(\t\022\036\n\005g" +
            "enre\030\004 \001(\0162\017.com.book.Genre*8\n\005Genre\022\t\n\005" +
            "BLUES\020\000\022\r\n\tCLASSICAL\020\001\022\013\n\007COUNTRY\020\002\022\010\n\004R" +
            "OCK\020\003B@\n!com.example.spanner.protobuf.bo" +
            "okB\tBookProtoP\001Z\016gaurav.purohitb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
            });
    internal_static_com_book_Book_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_com_book_Book_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_book_Book_descriptor,
        new java.lang.String[] { "Isbn", "Title", "Author", "Genre", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
