// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spanner/executor/v1/cloud_executor.proto
// Protobuf Java Version: 4.33.0

package com.google.spanner.executor.v1;

@com.google.protobuf.Generated
public interface BatchDmlActionOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.spanner.executor.v1.BatchDmlAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * DML statements.
   * </pre>
   *
   * <code>repeated .google.spanner.executor.v1.QueryAction updates = 1;</code>
   */
  java.util.List<com.google.spanner.executor.v1.QueryAction> getUpdatesList();

  /**
   *
   *
   * <pre>
   * DML statements.
   * </pre>
   *
   * <code>repeated .google.spanner.executor.v1.QueryAction updates = 1;</code>
   */
  com.google.spanner.executor.v1.QueryAction getUpdates(int index);

  /**
   *
   *
   * <pre>
   * DML statements.
   * </pre>
   *
   * <code>repeated .google.spanner.executor.v1.QueryAction updates = 1;</code>
   */
  int getUpdatesCount();

  /**
   *
   *
   * <pre>
   * DML statements.
   * </pre>
   *
   * <code>repeated .google.spanner.executor.v1.QueryAction updates = 1;</code>
   */
  java.util.List<? extends com.google.spanner.executor.v1.QueryActionOrBuilder>
      getUpdatesOrBuilderList();

  /**
   *
   *
   * <pre>
   * DML statements.
   * </pre>
   *
   * <code>repeated .google.spanner.executor.v1.QueryAction updates = 1;</code>
   */
  com.google.spanner.executor.v1.QueryActionOrBuilder getUpdatesOrBuilder(int index);
}
