// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spanner/executor/v1/cloud_executor.proto
// Protobuf Java Version: 4.33.0

package com.google.spanner.executor.v1;

@com.google.protobuf.Generated
public interface SpannerOptionsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.spanner.executor.v1.SpannerOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Options for configuring the session pool
   * </pre>
   *
   * <code>.google.spanner.executor.v1.SessionPoolOptions session_pool_options = 1;</code>
   *
   * @return Whether the sessionPoolOptions field is set.
   */
  boolean hasSessionPoolOptions();

  /**
   *
   *
   * <pre>
   * Options for configuring the session pool
   * </pre>
   *
   * <code>.google.spanner.executor.v1.SessionPoolOptions session_pool_options = 1;</code>
   *
   * @return The sessionPoolOptions.
   */
  com.google.spanner.executor.v1.SessionPoolOptions getSessionPoolOptions();

  /**
   *
   *
   * <pre>
   * Options for configuring the session pool
   * </pre>
   *
   * <code>.google.spanner.executor.v1.SessionPoolOptions session_pool_options = 1;</code>
   */
  com.google.spanner.executor.v1.SessionPoolOptionsOrBuilder getSessionPoolOptionsOrBuilder();
}
