// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/spanner/executor/v1/cloud_executor.proto
// Protobuf Java Version: 4.33.0

package com.google.spanner.executor.v1;

@com.google.protobuf.Generated
public interface UpdateCloudDatabaseActionOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.spanner.executor.v1.UpdateCloudDatabaseAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Cloud instance ID (not path), e.g. "test-instance".
   * </pre>
   *
   * <code>string instance_id = 1;</code>
   *
   * @return The instanceId.
   */
  java.lang.String getInstanceId();

  /**
   *
   *
   * <pre>
   * Cloud instance ID (not path), e.g. "test-instance".
   * </pre>
   *
   * <code>string instance_id = 1;</code>
   *
   * @return The bytes for instanceId.
   */
  com.google.protobuf.ByteString getInstanceIdBytes();

  /**
   *
   *
   * <pre>
   * Cloud project ID, e.g. "spanner-cloud-systest".
   * </pre>
   *
   * <code>string project_id = 2;</code>
   *
   * @return The projectId.
   */
  java.lang.String getProjectId();

  /**
   *
   *
   * <pre>
   * Cloud project ID, e.g. "spanner-cloud-systest".
   * </pre>
   *
   * <code>string project_id = 2;</code>
   *
   * @return The bytes for projectId.
   */
  com.google.protobuf.ByteString getProjectIdBytes();

  /**
   *
   *
   * <pre>
   * Cloud database name (not full path), e.g. "db0".
   * </pre>
   *
   * <code>string database_name = 3;</code>
   *
   * @return The databaseName.
   */
  java.lang.String getDatabaseName();

  /**
   *
   *
   * <pre>
   * Cloud database name (not full path), e.g. "db0".
   * </pre>
   *
   * <code>string database_name = 3;</code>
   *
   * @return The bytes for databaseName.
   */
  com.google.protobuf.ByteString getDatabaseNameBytes();

  /**
   *
   *
   * <pre>
   * Updated value of enable_drop_protection, this is the only field that has
   * supported to be updated.
   * </pre>
   *
   * <code>bool enable_drop_protection = 4;</code>
   *
   * @return The enableDropProtection.
   */
  boolean getEnableDropProtection();
}
