/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/v1/spanner.proto

// Protobuf Java Version: 3.25.7
package com.google.spanner.v1;

public final class SpannerProto {
  private SpannerProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_CreateSessionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_CreateSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_BatchCreateSessionsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_BatchCreateSessionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_BatchCreateSessionsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_BatchCreateSessionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_Session_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_Session_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_Session_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_Session_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_GetSessionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_GetSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ListSessionsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ListSessionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ListSessionsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ListSessionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_DeleteSessionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_DeleteSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_RequestOptions_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_RequestOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_DirectedReadOptions_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_DirectedReadOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_DirectedReadOptions_ReplicaSelection_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_DirectedReadOptions_ReplicaSelection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_DirectedReadOptions_IncludeReplicas_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_DirectedReadOptions_IncludeReplicas_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_DirectedReadOptions_ExcludeReplicas_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_DirectedReadOptions_ExcludeReplicas_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteSqlRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteSqlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteSqlRequest_QueryOptions_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteSqlRequest_QueryOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteSqlRequest_ParamTypesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteSqlRequest_ParamTypesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_ParamTypesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_ParamTypesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ExecuteBatchDmlResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ExecuteBatchDmlResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_PartitionOptions_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_PartitionOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_PartitionQueryRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_PartitionQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_PartitionQueryRequest_ParamTypesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_PartitionQueryRequest_ParamTypesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_PartitionReadRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_PartitionReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_Partition_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_Partition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_PartitionResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_PartitionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_ReadRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_BeginTransactionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_BeginTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_CommitRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_CommitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_RollbackRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_RollbackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_BatchWriteRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_BatchWriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_BatchWriteRequest_MutationGroup_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_BatchWriteRequest_MutationGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_v1_BatchWriteResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_v1_BatchWriteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\037google/spanner/v1/spanner.proto\022\021googl"
          + "e.spanner.v1\032\'google/spanner/v1/commit_r"
          + "esponse.proto\032\034google/api/annotations.pr"
          + "oto\032\027google/api/client.proto\032\037google/api"
          + "/field_behavior.proto\032\031google/api/resour"
          + "ce.proto\032\036google/protobuf/duration.proto"
          + "\032\033google/protobuf/empty.proto\032\034google/pr"
          + "otobuf/struct.proto\032\037google/protobuf/tim"
          + "estamp.proto\032\027google/rpc/status.proto\032\034g"
          + "oogle/spanner/v1/keys.proto\032 google/span"
          + "ner/v1/location.proto\032 google/spanner/v1"
          + "/mutation.proto\032\"google/spanner/v1/resul"
          + "t_set.proto\032#google/spanner/v1/transacti"
          + "on.proto\032\034google/spanner/v1/type.proto\"\203"
          + "\001\n\024CreateSessionRequest\0229\n\010database\030\001 \001("
          + "\tB\'\340A\002\372A!\n\037spanner.googleapis.com/Databa"
          + "se\0220\n\007session\030\002 \001(\0132\032.google.spanner.v1."
          + "SessionB\003\340A\002\"\251\001\n\032BatchCreateSessionsRequ"
          + "est\0229\n\010database\030\001 \001(\tB\'\340A\002\372A!\n\037spanner.g"
          + "oogleapis.com/Database\0224\n\020session_templa"
          + "te\030\002 \001(\0132\032.google.spanner.v1.Session\022\032\n\r"
          + "session_count\030\003 \001(\005B\003\340A\002\"J\n\033BatchCreateS"
          + "essionsResponse\022+\n\007session\030\001 \003(\0132\032.googl"
          + "e.spanner.v1.Session\"\243\003\n\007Session\022\021\n\004name"
          + "\030\001 \001(\tB\003\340A\003\0226\n\006labels\030\002 \003(\0132&.google.spa"
          + "nner.v1.Session.LabelsEntry\0224\n\013create_ti"
          + "me\030\003 \001(\0132\032.google.protobuf.TimestampB\003\340A"
          + "\003\022B\n\031approximate_last_use_time\030\004 \001(\0132\032.g"
          + "oogle.protobuf.TimestampB\003\340A\003\022\024\n\014creator"
          + "_role\030\005 \001(\t\022\030\n\013multiplexed\030\006 \001(\010B\003\340A\001\032-\n"
          + "\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t"
          + ":\0028\001:t\352Aq\n\036spanner.googleapis.com/Sessio"
          + "n\022Oprojects/{project}/instances/{instanc"
          + "e}/databases/{database}/sessions/{sessio"
          + "n}\"I\n\021GetSessionRequest\0224\n\004name\030\001 \001(\tB&\340"
          + "A\002\372A \n\036spanner.googleapis.com/Session\"\207\001"
          + "\n\023ListSessionsRequest\0229\n\010database\030\001 \001(\tB"
          + "\'\340A\002\372A!\n\037spanner.googleapis.com/Database"
          + "\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t\022"
          + "\016\n\006filter\030\004 \001(\t\"]\n\024ListSessionsResponse\022"
          + ",\n\010sessions\030\001 \003(\0132\032.google.spanner.v1.Se"
          + "ssion\022\027\n\017next_page_token\030\002 \001(\t\"L\n\024Delete"
          + "SessionRequest\0224\n\004name\030\001 \001(\tB&\340A\002\372A \n\036sp"
          + "anner.googleapis.com/Session\"\334\001\n\016Request"
          + "Options\022<\n\010priority\030\001 \001(\0162*.google.spann"
          + "er.v1.RequestOptions.Priority\022\023\n\013request"
          + "_tag\030\002 \001(\t\022\027\n\017transaction_tag\030\003 \001(\t\"^\n\010P"
          + "riority\022\030\n\024PRIORITY_UNSPECIFIED\020\000\022\020\n\014PRI"
          + "ORITY_LOW\020\001\022\023\n\017PRIORITY_MEDIUM\020\002\022\021\n\rPRIO"
          + "RITY_HIGH\020\003\"\352\004\n\023DirectedReadOptions\022R\n\020i"
          + "nclude_replicas\030\001 \001(\01326.google.spanner.v"
          + "1.DirectedReadOptions.IncludeReplicasH\000\022"
          + "R\n\020exclude_replicas\030\002 \001(\01326.google.spann"
          + "er.v1.DirectedReadOptions.ExcludeReplica"
          + "sH\000\032\255\001\n\020ReplicaSelection\022\020\n\010location\030\001 \001"
          + "(\t\022J\n\004type\030\002 \001(\0162<.google.spanner.v1.Dir"
          + "ectedReadOptions.ReplicaSelection.Type\";"
          + "\n\004Type\022\024\n\020TYPE_UNSPECIFIED\020\000\022\016\n\nREAD_WRI"
          + "TE\020\001\022\r\n\tREAD_ONLY\020\002\032\206\001\n\017IncludeReplicas\022"
          + "S\n\022replica_selections\030\001 \003(\01327.google.spa"
          + "nner.v1.DirectedReadOptions.ReplicaSelec"
          + "tion\022\036\n\026auto_failover_disabled\030\002 \001(\010\032f\n\017"
          + "ExcludeReplicas\022S\n\022replica_selections\030\001 "
          + "\003(\01327.google.spanner.v1.DirectedReadOpti"
          + "ons.ReplicaSelectionB\n\n\010replicas\"\303\007\n\021Exe"
          + "cuteSqlRequest\0227\n\007session\030\001 \001(\tB&\340A\002\372A \n"
          + "\036spanner.googleapis.com/Session\022;\n\013trans"
          + "action\030\002 \001(\0132&.google.spanner.v1.Transac"
          + "tionSelector\022\020\n\003sql\030\003 \001(\tB\003\340A\002\022\'\n\006params"
          + "\030\004 \001(\0132\027.google.protobuf.Struct\022I\n\013param"
          + "_types\030\005 \003(\01324.google.spanner.v1.Execute"
          + "SqlRequest.ParamTypesEntry\022\024\n\014resume_tok"
          + "en\030\006 \001(\014\022B\n\nquery_mode\030\007 \001(\0162..google.sp"
          + "anner.v1.ExecuteSqlRequest.QueryMode\022\027\n\017"
          + "partition_token\030\010 \001(\014\022\r\n\005seqno\030\t \001(\003\022H\n\r"
          + "query_options\030\n \001(\01321.google.spanner.v1."
          + "ExecuteSqlRequest.QueryOptions\022:\n\017reques"
          + "t_options\030\013 \001(\0132!.google.spanner.v1.Requ"
          + "estOptions\022E\n\025directed_read_options\030\017 \001("
          + "\0132&.google.spanner.v1.DirectedReadOption"
          + "s\022\032\n\022data_boost_enabled\030\020 \001(\010\022\033\n\016last_st"
          + "atement\030\021 \001(\010B\003\340A\001\0224\n\014routing_hint\030c \001(\013"
          + "2\036.google.spanner.v1.RoutingHint\032O\n\014Quer"
          + "yOptions\022\031\n\021optimizer_version\030\001 \001(\t\022$\n\034o"
          + "ptimizer_statistics_package\030\002 \001(\t\032J\n\017Par"
          + "amTypesEntry\022\013\n\003key\030\001 \001(\t\022&\n\005value\030\002 \001(\013"
          + "2\027.google.spanner.v1.Type:\0028\001\"W\n\tQueryMo"
          + "de\022\n\n\006NORMAL\020\000\022\010\n\004PLAN\020\001\022\013\n\007PROFILE\020\002\022\016\n"
          + "\nWITH_STATS\020\003\022\027\n\023WITH_PLAN_AND_STATS\020\004\"\276"
          + "\004\n\026ExecuteBatchDmlRequest\0227\n\007session\030\001 \001"
          + "(\tB&\340A\002\372A \n\036spanner.googleapis.com/Sessi"
          + "on\022@\n\013transaction\030\002 \001(\0132&.google.spanner"
          + ".v1.TransactionSelectorB\003\340A\002\022L\n\nstatemen"
          + "ts\030\003 \003(\01323.google.spanner.v1.ExecuteBatc"
          + "hDmlRequest.StatementB\003\340A\002\022\022\n\005seqno\030\004 \001("
          + "\003B\003\340A\002\022:\n\017request_options\030\005 \001(\0132!.google"
          + ".spanner.v1.RequestOptions\022\034\n\017last_state"
          + "ments\030\006 \001(\010B\003\340A\001\032\354\001\n\tStatement\022\020\n\003sql\030\001 "
          + "\001(\tB\003\340A\002\022\'\n\006params\030\002 \001(\0132\027.google.protob"
          + "uf.Struct\022X\n\013param_types\030\003 \003(\0132C.google."
          + "spanner.v1.ExecuteBatchDmlRequest.Statem"
          + "ent.ParamTypesEntry\032J\n\017ParamTypesEntry\022\013"
          + "\n\003key\030\001 \001(\t\022&\n\005value\030\002 \001(\0132\027.google.span"
          + "ner.v1.Type:\0028\001\"\303\001\n\027ExecuteBatchDmlRespo"
          + "nse\0221\n\013result_sets\030\001 \003(\0132\034.google.spanne"
          + "r.v1.ResultSet\022\"\n\006status\030\002 \001(\0132\022.google."
          + "rpc.Status\022Q\n\017precommit_token\030\003 \001(\01323.go"
          + "ogle.spanner.v1.MultiplexedSessionPrecom"
          + "mitTokenB\003\340A\001\"H\n\020PartitionOptions\022\034\n\024par"
          + "tition_size_bytes\030\001 \001(\003\022\026\n\016max_partition"
          + "s\030\002 \001(\003\"\243\003\n\025PartitionQueryRequest\0227\n\007ses"
          + "sion\030\001 \001(\tB&\340A\002\372A \n\036spanner.googleapis.c"
          + "om/Session\022;\n\013transaction\030\002 \001(\0132&.google"
          + ".spanner.v1.TransactionSelector\022\020\n\003sql\030\003"
          + " \001(\tB\003\340A\002\022\'\n\006params\030\004 \001(\0132\027.google.proto"
          + "buf.Struct\022M\n\013param_types\030\005 \003(\01328.google"
          + ".spanner.v1.PartitionQueryRequest.ParamT"
          + "ypesEntry\022>\n\021partition_options\030\006 \001(\0132#.g"
          + "oogle.spanner.v1.PartitionOptions\032J\n\017Par"
          + "amTypesEntry\022\013\n\003key\030\001 \001(\t\022&\n\005value\030\002 \001(\013"
          + "2\027.google.spanner.v1.Type:\0028\001\"\261\002\n\024Partit"
          + "ionReadRequest\0227\n\007session\030\001 \001(\tB&\340A\002\372A \n"
          + "\036spanner.googleapis.com/Session\022;\n\013trans"
          + "action\030\002 \001(\0132&.google.spanner.v1.Transac"
          + "tionSelector\022\022\n\005table\030\003 \001(\tB\003\340A\002\022\r\n\005inde"
          + "x\030\004 \001(\t\022\017\n\007columns\030\005 \003(\t\022/\n\007key_set\030\006 \001("
          + "\0132\031.google.spanner.v1.KeySetB\003\340A\002\022>\n\021par"
          + "tition_options\030\t \001(\0132#.google.spanner.v1"
          + ".PartitionOptions\"$\n\tPartition\022\027\n\017partit"
          + "ion_token\030\001 \001(\014\"z\n\021PartitionResponse\0220\n\n"
          + "partitions\030\001 \003(\0132\034.google.spanner.v1.Par"
          + "tition\0223\n\013transaction\030\002 \001(\0132\036.google.spa"
          + "nner.v1.Transaction\"\254\006\n\013ReadRequest\0227\n\007s"
          + "ession\030\001 \001(\tB&\340A\002\372A \n\036spanner.googleapis"
          + ".com/Session\022;\n\013transaction\030\002 \001(\0132&.goog"
          + "le.spanner.v1.TransactionSelector\022\022\n\005tab"
          + "le\030\003 \001(\tB\003\340A\002\022\r\n\005index\030\004 \001(\t\022\024\n\007columns\030"
          + "\005 \003(\tB\003\340A\002\022/\n\007key_set\030\006 \001(\0132\031.google.spa"
          + "nner.v1.KeySetB\003\340A\002\022\r\n\005limit\030\010 \001(\003\022\024\n\014re"
          + "sume_token\030\t \001(\014\022\027\n\017partition_token\030\n \001("
          + "\014\022:\n\017request_options\030\013 \001(\0132!.google.span"
          + "ner.v1.RequestOptions\022E\n\025directed_read_o"
          + "ptions\030\016 \001(\0132&.google.spanner.v1.Directe"
          + "dReadOptions\022\032\n\022data_boost_enabled\030\017 \001(\010"
          + "\022=\n\010order_by\030\020 \001(\0162&.google.spanner.v1.R"
          + "eadRequest.OrderByB\003\340A\001\022?\n\tlock_hint\030\021 \001"
          + "(\0162\'.google.spanner.v1.ReadRequest.LockH"
          + "intB\003\340A\001\0224\n\014routing_hint\030c \001(\0132\036.google."
          + "spanner.v1.RoutingHint\"T\n\007OrderBy\022\030\n\024ORD"
          + "ER_BY_UNSPECIFIED\020\000\022\030\n\024ORDER_BY_PRIMARY_"
          + "KEY\020\001\022\025\n\021ORDER_BY_NO_ORDER\020\002\"T\n\010LockHint"
          + "\022\031\n\025LOCK_HINT_UNSPECIFIED\020\000\022\024\n\020LOCK_HINT"
          + "_SHARED\020\001\022\027\n\023LOCK_HINT_EXCLUSIVE\020\002\"\203\002\n\027B"
          + "eginTransactionRequest\0227\n\007session\030\001 \001(\tB"
          + "&\340A\002\372A \n\036spanner.googleapis.com/Session\022"
          + ";\n\007options\030\002 \001(\0132%.google.spanner.v1.Tra"
          + "nsactionOptionsB\003\340A\002\022:\n\017request_options\030"
          + "\003 \001(\0132!.google.spanner.v1.RequestOptions"
          + "\0226\n\014mutation_key\030\004 \001(\0132\033.google.spanner."
          + "v1.MutationB\003\340A\001\"\320\003\n\rCommitRequest\0227\n\007se"
          + "ssion\030\001 \001(\tB&\340A\002\372A \n\036spanner.googleapis."
          + "com/Session\022\030\n\016transaction_id\030\002 \001(\014H\000\022G\n"
          + "\026single_use_transaction\030\003 \001(\0132%.google.s"
          + "panner.v1.TransactionOptionsH\000\022.\n\tmutati"
          + "ons\030\004 \003(\0132\033.google.spanner.v1.Mutation\022\033"
          + "\n\023return_commit_stats\030\005 \001(\010\0228\n\020max_commi"
          + "t_delay\030\010 \001(\0132\031.google.protobuf.Duration"
          + "B\003\340A\001\022:\n\017request_options\030\006 \001(\0132!.google."
          + "spanner.v1.RequestOptions\022Q\n\017precommit_t"
          + "oken\030\t \001(\01323.google.spanner.v1.Multiplex"
          + "edSessionPrecommitTokenB\003\340A\001B\r\n\013transact"
          + "ion\"g\n\017RollbackRequest\0227\n\007session\030\001 \001(\tB"
          + "&\340A\002\372A \n\036spanner.googleapis.com/Session\022"
          + "\033\n\016transaction_id\030\002 \001(\014B\003\340A\002\"\316\002\n\021BatchWr"
          + "iteRequest\0227\n\007session\030\001 \001(\tB&\340A\002\372A \n\036spa"
          + "nner.googleapis.com/Session\022:\n\017request_o"
          + "ptions\030\003 \001(\0132!.google.spanner.v1.Request"
          + "Options\022P\n\017mutation_groups\030\004 \003(\01322.googl"
          + "e.spanner.v1.BatchWriteRequest.MutationG"
          + "roupB\003\340A\002\022,\n\037exclude_txn_from_change_str"
          + "eams\030\005 \001(\010B\003\340A\001\032D\n\rMutationGroup\0223\n\tmuta"
          + "tions\030\001 \003(\0132\033.google.spanner.v1.Mutation"
          + "B\003\340A\002\"\177\n\022BatchWriteResponse\022\017\n\007indexes\030\001"
          + " \003(\005\022\"\n\006status\030\002 \001(\0132\022.google.rpc.Status"
          + "\0224\n\020commit_timestamp\030\003 \001(\0132\032.google.prot"
          + "obuf.Timestamp2\213\030\n\007Spanner\022\246\001\n\rCreateSes"
          + "sion\022\'.google.spanner.v1.CreateSessionRe"
          + "quest\032\032.google.spanner.v1.Session\"P\332A\010da"
          + "tabase\202\323\344\223\002?\":/v1/{database=projects/*/i"
          + "nstances/*/databases/*}/sessions:\001*\022\340\001\n\023"
          + "BatchCreateSessions\022-.google.spanner.v1."
          + "BatchCreateSessionsRequest\032..google.span"
          + "ner.v1.BatchCreateSessionsResponse\"j\332A\026d"
          + "atabase,session_count\202\323\344\223\002K\"F/v1/{databa"
          + "se=projects/*/instances/*/databases/*}/s"
          + "essions:batchCreate:\001*\022\227\001\n\nGetSession\022$."
          + "google.spanner.v1.GetSessionRequest\032\032.go"
          + "ogle.spanner.v1.Session\"G\332A\004name\202\323\344\223\002:\0228"
          + "/v1/{name=projects/*/instances/*/databas"
          + "es/*/sessions/*}\022\256\001\n\014ListSessions\022&.goog"
          + "le.spanner.v1.ListSessionsRequest\032\'.goog"
          + "le.spanner.v1.ListSessionsResponse\"M\332A\010d"
          + "atabase\202\323\344\223\002<\022:/v1/{database=projects/*/"
          + "instances/*/databases/*}/sessions\022\231\001\n\rDe"
          + "leteSession\022\'.google.spanner.v1.DeleteSe"
          + "ssionRequest\032\026.google.protobuf.Empty\"G\332A"
          + "\004name\202\323\344\223\002:*8/v1/{name=projects/*/instan"
          + "ces/*/databases/*/sessions/*}\022\243\001\n\nExecut"
          + "eSql\022$.google.spanner.v1.ExecuteSqlReque"
          + "st\032\034.google.spanner.v1.ResultSet\"Q\202\323\344\223\002K"
          + "\"F/v1/{session=projects/*/instances/*/da"
          + "tabases/*/sessions/*}:executeSql:\001*\022\276\001\n\023"
          + "ExecuteStreamingSql\022$.google.spanner.v1."
          + "ExecuteSqlRequest\032#.google.spanner.v1.Pa"
          + "rtialResultSet\"Z\202\323\344\223\002T\"O/v1/{session=pro"
          + "jects/*/instances/*/databases/*/sessions"
          + "/*}:executeStreamingSql:\001*0\001\022\300\001\n\017Execute"
          + "BatchDml\022).google.spanner.v1.ExecuteBatc"
          + "hDmlRequest\032*.google.spanner.v1.ExecuteB"
          + "atchDmlResponse\"V\202\323\344\223\002P\"K/v1/{session=pr"
          + "ojects/*/instances/*/databases/*/session"
          + "s/*}:executeBatchDml:\001*\022\221\001\n\004Read\022\036.googl"
          + "e.spanner.v1.ReadRequest\032\034.google.spanne"
          + "r.v1.ResultSet\"K\202\323\344\223\002E\"@/v1/{session=pro"
          + "jects/*/instances/*/databases/*/sessions"
          + "/*}:read:\001*\022\254\001\n\rStreamingRead\022\036.google.s"
          + "panner.v1.ReadRequest\032#.google.spanner.v"
          + "1.PartialResultSet\"T\202\323\344\223\002N\"I/v1/{session"
          + "=projects/*/instances/*/databases/*/sess"
          + "ions/*}:streamingRead:\001*0\001\022\311\001\n\020BeginTran"
          + "saction\022*.google.spanner.v1.BeginTransac"
          + "tionRequest\032\036.google.spanner.v1.Transact"
          + "ion\"i\332A\017session,options\202\323\344\223\002Q\"L/v1/{sess"
          + "ion=projects/*/instances/*/databases/*/s"
          + "essions/*}:beginTransaction:\001*\022\353\001\n\006Commi"
          + "t\022 .google.spanner.v1.CommitRequest\032!.go"
          + "ogle.spanner.v1.CommitResponse\"\233\001\332A sess"
          + "ion,transaction_id,mutations\332A(session,s"
          + "ingle_use_transaction,mutations\202\323\344\223\002G\"B/"
          + "v1/{session=projects/*/instances/*/datab"
          + "ases/*/sessions/*}:commit:\001*\022\260\001\n\010Rollbac"
          + "k\022\".google.spanner.v1.RollbackRequest\032\026."
          + "google.protobuf.Empty\"h\332A\026session,transa"
          + "ction_id\202\323\344\223\002I\"D/v1/{session=projects/*/"
          + "instances/*/databases/*/sessions/*}:roll"
          + "back:\001*\022\267\001\n\016PartitionQuery\022(.google.span"
          + "ner.v1.PartitionQueryRequest\032$.google.sp"
          + "anner.v1.PartitionResponse\"U\202\323\344\223\002O\"J/v1/"
          + "{session=projects/*/instances/*/database"
          + "s/*/sessions/*}:partitionQuery:\001*\022\264\001\n\rPa"
          + "rtitionRead\022\'.google.spanner.v1.Partitio"
          + "nReadRequest\032$.google.spanner.v1.Partiti"
          + "onResponse\"T\202\323\344\223\002N\"I/v1/{session=project"
          + "s/*/instances/*/databases/*/sessions/*}:"
          + "partitionRead:\001*\022\310\001\n\nBatchWrite\022$.google"
          + ".spanner.v1.BatchWriteRequest\032%.google.s"
          + "panner.v1.BatchWriteResponse\"k\332A\027session"
          + ",mutation_groups\202\323\344\223\002K\"F/v1/{session=pro"
          + "jects/*/instances/*/databases/*/sessions"
          + "/*}:batchWrite:\001*0\001\032w\312A\026spanner.googleap"
          + "is.com\322A[https://www.googleapis.com/auth"
          + "/cloud-platform,https://www.googleapis.c"
          + "om/auth/spanner.dataB\221\002\n\025com.google.span"
          + "ner.v1B\014SpannerProtoP\001Z5cloud.google.com"
          + "/go/spanner/apiv1/spannerpb;spannerpb\252\002\027"
          + "Google.Cloud.Spanner.V1\312\002\027Google\\Cloud\\S"
          + "panner\\V1\352\002\032Google::Cloud::Spanner::V1\352A"
          + "_\n\037spanner.googleapis.com/Database\022<proj"
          + "ects/{project}/instances/{instance}/data"
          + "bases/{database}P\000b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.spanner.v1.CommitResponseProto.getDescriptor(),
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.protobuf.DurationProto.getDescriptor(),
              com.google.protobuf.EmptyProto.getDescriptor(),
              com.google.protobuf.StructProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.rpc.StatusProto.getDescriptor(),
              com.google.spanner.v1.KeysProto.getDescriptor(),
              com.google.spanner.v1.LocationProto.getDescriptor(),
              com.google.spanner.v1.MutationProto.getDescriptor(),
              com.google.spanner.v1.ResultSetProto.getDescriptor(),
              com.google.spanner.v1.TransactionProto.getDescriptor(),
              com.google.spanner.v1.TypeProto.getDescriptor(),
            });
    internal_static_google_spanner_v1_CreateSessionRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_spanner_v1_CreateSessionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_CreateSessionRequest_descriptor,
            new java.lang.String[] {
              "Database", "Session",
            });
    internal_static_google_spanner_v1_BatchCreateSessionsRequest_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_spanner_v1_BatchCreateSessionsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_BatchCreateSessionsRequest_descriptor,
            new java.lang.String[] {
              "Database", "SessionTemplate", "SessionCount",
            });
    internal_static_google_spanner_v1_BatchCreateSessionsResponse_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_spanner_v1_BatchCreateSessionsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_BatchCreateSessionsResponse_descriptor,
            new java.lang.String[] {
              "Session",
            });
    internal_static_google_spanner_v1_Session_descriptor = getDescriptor().getMessageTypes().get(3);
    internal_static_google_spanner_v1_Session_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_Session_descriptor,
            new java.lang.String[] {
              "Name",
              "Labels",
              "CreateTime",
              "ApproximateLastUseTime",
              "CreatorRole",
              "Multiplexed",
            });
    internal_static_google_spanner_v1_Session_LabelsEntry_descriptor =
        internal_static_google_spanner_v1_Session_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_v1_Session_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_Session_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_spanner_v1_GetSessionRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_spanner_v1_GetSessionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_GetSessionRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_spanner_v1_ListSessionsRequest_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_spanner_v1_ListSessionsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ListSessionsRequest_descriptor,
            new java.lang.String[] {
              "Database", "PageSize", "PageToken", "Filter",
            });
    internal_static_google_spanner_v1_ListSessionsResponse_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_spanner_v1_ListSessionsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ListSessionsResponse_descriptor,
            new java.lang.String[] {
              "Sessions", "NextPageToken",
            });
    internal_static_google_spanner_v1_DeleteSessionRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_spanner_v1_DeleteSessionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_DeleteSessionRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_spanner_v1_RequestOptions_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_spanner_v1_RequestOptions_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_RequestOptions_descriptor,
            new java.lang.String[] {
              "Priority", "RequestTag", "TransactionTag",
            });
    internal_static_google_spanner_v1_DirectedReadOptions_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_spanner_v1_DirectedReadOptions_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_DirectedReadOptions_descriptor,
            new java.lang.String[] {
              "IncludeReplicas", "ExcludeReplicas", "Replicas",
            });
    internal_static_google_spanner_v1_DirectedReadOptions_ReplicaSelection_descriptor =
        internal_static_google_spanner_v1_DirectedReadOptions_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_v1_DirectedReadOptions_ReplicaSelection_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_DirectedReadOptions_ReplicaSelection_descriptor,
            new java.lang.String[] {
              "Location", "Type",
            });
    internal_static_google_spanner_v1_DirectedReadOptions_IncludeReplicas_descriptor =
        internal_static_google_spanner_v1_DirectedReadOptions_descriptor.getNestedTypes().get(1);
    internal_static_google_spanner_v1_DirectedReadOptions_IncludeReplicas_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_DirectedReadOptions_IncludeReplicas_descriptor,
            new java.lang.String[] {
              "ReplicaSelections", "AutoFailoverDisabled",
            });
    internal_static_google_spanner_v1_DirectedReadOptions_ExcludeReplicas_descriptor =
        internal_static_google_spanner_v1_DirectedReadOptions_descriptor.getNestedTypes().get(2);
    internal_static_google_spanner_v1_DirectedReadOptions_ExcludeReplicas_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_DirectedReadOptions_ExcludeReplicas_descriptor,
            new java.lang.String[] {
              "ReplicaSelections",
            });
    internal_static_google_spanner_v1_ExecuteSqlRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_spanner_v1_ExecuteSqlRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteSqlRequest_descriptor,
            new java.lang.String[] {
              "Session",
              "Transaction",
              "Sql",
              "Params",
              "ParamTypes",
              "ResumeToken",
              "QueryMode",
              "PartitionToken",
              "Seqno",
              "QueryOptions",
              "RequestOptions",
              "DirectedReadOptions",
              "DataBoostEnabled",
              "LastStatement",
              "RoutingHint",
            });
    internal_static_google_spanner_v1_ExecuteSqlRequest_QueryOptions_descriptor =
        internal_static_google_spanner_v1_ExecuteSqlRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_v1_ExecuteSqlRequest_QueryOptions_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteSqlRequest_QueryOptions_descriptor,
            new java.lang.String[] {
              "OptimizerVersion", "OptimizerStatisticsPackage",
            });
    internal_static_google_spanner_v1_ExecuteSqlRequest_ParamTypesEntry_descriptor =
        internal_static_google_spanner_v1_ExecuteSqlRequest_descriptor.getNestedTypes().get(1);
    internal_static_google_spanner_v1_ExecuteSqlRequest_ParamTypesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteSqlRequest_ParamTypesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteBatchDmlRequest_descriptor,
            new java.lang.String[] {
              "Session", "Transaction", "Statements", "Seqno", "RequestOptions", "LastStatements",
            });
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_descriptor =
        internal_static_google_spanner_v1_ExecuteBatchDmlRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_descriptor,
            new java.lang.String[] {
              "Sql", "Params", "ParamTypes",
            });
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_ParamTypesEntry_descriptor =
        internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_ParamTypesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteBatchDmlRequest_Statement_ParamTypesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_spanner_v1_ExecuteBatchDmlResponse_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_spanner_v1_ExecuteBatchDmlResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ExecuteBatchDmlResponse_descriptor,
            new java.lang.String[] {
              "ResultSets", "Status", "PrecommitToken",
            });
    internal_static_google_spanner_v1_PartitionOptions_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_spanner_v1_PartitionOptions_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_PartitionOptions_descriptor,
            new java.lang.String[] {
              "PartitionSizeBytes", "MaxPartitions",
            });
    internal_static_google_spanner_v1_PartitionQueryRequest_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_spanner_v1_PartitionQueryRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_PartitionQueryRequest_descriptor,
            new java.lang.String[] {
              "Session", "Transaction", "Sql", "Params", "ParamTypes", "PartitionOptions",
            });
    internal_static_google_spanner_v1_PartitionQueryRequest_ParamTypesEntry_descriptor =
        internal_static_google_spanner_v1_PartitionQueryRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_v1_PartitionQueryRequest_ParamTypesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_PartitionQueryRequest_ParamTypesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_spanner_v1_PartitionReadRequest_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_spanner_v1_PartitionReadRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_PartitionReadRequest_descriptor,
            new java.lang.String[] {
              "Session", "Transaction", "Table", "Index", "Columns", "KeySet", "PartitionOptions",
            });
    internal_static_google_spanner_v1_Partition_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_spanner_v1_Partition_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_Partition_descriptor,
            new java.lang.String[] {
              "PartitionToken",
            });
    internal_static_google_spanner_v1_PartitionResponse_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_spanner_v1_PartitionResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_PartitionResponse_descriptor,
            new java.lang.String[] {
              "Partitions", "Transaction",
            });
    internal_static_google_spanner_v1_ReadRequest_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_spanner_v1_ReadRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_ReadRequest_descriptor,
            new java.lang.String[] {
              "Session",
              "Transaction",
              "Table",
              "Index",
              "Columns",
              "KeySet",
              "Limit",
              "ResumeToken",
              "PartitionToken",
              "RequestOptions",
              "DirectedReadOptions",
              "DataBoostEnabled",
              "OrderBy",
              "LockHint",
              "RoutingHint",
            });
    internal_static_google_spanner_v1_BeginTransactionRequest_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_spanner_v1_BeginTransactionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_BeginTransactionRequest_descriptor,
            new java.lang.String[] {
              "Session", "Options", "RequestOptions", "MutationKey",
            });
    internal_static_google_spanner_v1_CommitRequest_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_spanner_v1_CommitRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_CommitRequest_descriptor,
            new java.lang.String[] {
              "Session",
              "TransactionId",
              "SingleUseTransaction",
              "Mutations",
              "ReturnCommitStats",
              "MaxCommitDelay",
              "RequestOptions",
              "PrecommitToken",
              "Transaction",
            });
    internal_static_google_spanner_v1_RollbackRequest_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_spanner_v1_RollbackRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_RollbackRequest_descriptor,
            new java.lang.String[] {
              "Session", "TransactionId",
            });
    internal_static_google_spanner_v1_BatchWriteRequest_descriptor =
        getDescriptor().getMessageTypes().get(22);
    internal_static_google_spanner_v1_BatchWriteRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_BatchWriteRequest_descriptor,
            new java.lang.String[] {
              "Session", "RequestOptions", "MutationGroups", "ExcludeTxnFromChangeStreams",
            });
    internal_static_google_spanner_v1_BatchWriteRequest_MutationGroup_descriptor =
        internal_static_google_spanner_v1_BatchWriteRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_v1_BatchWriteRequest_MutationGroup_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_BatchWriteRequest_MutationGroup_descriptor,
            new java.lang.String[] {
              "Mutations",
            });
    internal_static_google_spanner_v1_BatchWriteResponse_descriptor =
        getDescriptor().getMessageTypes().get(23);
    internal_static_google_spanner_v1_BatchWriteResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_v1_BatchWriteResponse_descriptor,
            new java.lang.String[] {
              "Indexes", "Status", "CommitTimestamp",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceDefinition);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.spanner.v1.CommitResponseProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
    com.google.spanner.v1.KeysProto.getDescriptor();
    com.google.spanner.v1.LocationProto.getDescriptor();
    com.google.spanner.v1.MutationProto.getDescriptor();
    com.google.spanner.v1.ResultSetProto.getDescriptor();
    com.google.spanner.v1.TransactionProto.getDescriptor();
    com.google.spanner.v1.TypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
