/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/admin/database/v1/common.proto

package com.google.spanner.admin.database.v1;

public interface EncryptionConfigOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.spanner.admin.database.v1.EncryptionConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * (--
   * TODO(b/240165507) make the following comment visible after cloud spanner
   * multi-region cmek launch.
   * --)
   * (--
   * This field is maintained for backwards compatibility. For new callers, we
   * recommend using `kms_key_names` to specify the KMS key.
   * `kms_key_name` should only be used if the location of the KMS key matches
   * the database instance’s configuration (location) exactly. E.g. The KMS
   * location is in us-central1 or nam3 and the database instance is also in
   * us-central1 or nam3.
   * --)
   * The Cloud KMS key to be used for encrypting and decrypting
   * the database. Values are of the form
   * `projects/&lt;project&gt;/locations/&lt;location&gt;/keyRings/&lt;key_ring&gt;/cryptoKeys/&lt;kms_key_name&gt;`.
   * (-- api-linter: core::0122::name-suffix=disabled
   *     aip.dev/not-precedent: crypto key identifiers like this are listed as a
   *     canonical example of when field names would be ambiguous without the
   *     _name suffix and should therefore include it. --)
   * </pre>
   *
   * <code>string kms_key_name = 2 [(.google.api.resource_reference) = { ... }</code>
   *
   * @return The kmsKeyName.
   */
  java.lang.String getKmsKeyName();
  /**
   *
   *
   * <pre>
   * (--
   * TODO(b/240165507) make the following comment visible after cloud spanner
   * multi-region cmek launch.
   * --)
   * (--
   * This field is maintained for backwards compatibility. For new callers, we
   * recommend using `kms_key_names` to specify the KMS key.
   * `kms_key_name` should only be used if the location of the KMS key matches
   * the database instance’s configuration (location) exactly. E.g. The KMS
   * location is in us-central1 or nam3 and the database instance is also in
   * us-central1 or nam3.
   * --)
   * The Cloud KMS key to be used for encrypting and decrypting
   * the database. Values are of the form
   * `projects/&lt;project&gt;/locations/&lt;location&gt;/keyRings/&lt;key_ring&gt;/cryptoKeys/&lt;kms_key_name&gt;`.
   * (-- api-linter: core::0122::name-suffix=disabled
   *     aip.dev/not-precedent: crypto key identifiers like this are listed as a
   *     canonical example of when field names would be ambiguous without the
   *     _name suffix and should therefore include it. --)
   * </pre>
   *
   * <code>string kms_key_name = 2 [(.google.api.resource_reference) = { ... }</code>
   *
   * @return The bytes for kmsKeyName.
   */
  com.google.protobuf.ByteString getKmsKeyNameBytes();

  /**
   *
   *
   * <pre>
   * (--
   * TODO(b/240165507) remove visibility check after cloud spanner multi-region
   * cmek launch.
   * --)
   * Specifies the KMS configuration for the one or more keys used to encrypt
   * the database. Values are of the form
   * `projects/&lt;project&gt;/locations/&lt;location&gt;/keyRings/&lt;key_ring&gt;/cryptoKeys/&lt;kms_key_name&gt;`.
   * The keys referenced by kms_key_names must fully cover all
   * regions of the database instance configuration. Some examples:
   * * For single region database instance configs, specify a single regional
   * location KMS key.
   * * For multi-regional database instance configs of type GOOGLE_MANAGED,
   * either specify a multi-regional location KMS key or multiple regional
   * location KMS keys that cover all regions in the instance config.
   * * For a database instance config of type USER_MANAGED, please specify only
   * regional location KMS keys to cover each region in the instance config.
   * Multi-regional location KMS keys are not supported for USER_MANAGED
   * instance configs.
   * </pre>
   *
   * <code>repeated string kms_key_names = 3 [(.google.api.resource_reference) = { ... }</code>
   *
   * @return A list containing the kmsKeyNames.
   */
  java.util.List<java.lang.String> getKmsKeyNamesList();
  /**
   *
   *
   * <pre>
   * (--
   * TODO(b/240165507) remove visibility check after cloud spanner multi-region
   * cmek launch.
   * --)
   * Specifies the KMS configuration for the one or more keys used to encrypt
   * the database. Values are of the form
   * `projects/&lt;project&gt;/locations/&lt;location&gt;/keyRings/&lt;key_ring&gt;/cryptoKeys/&lt;kms_key_name&gt;`.
   * The keys referenced by kms_key_names must fully cover all
   * regions of the database instance configuration. Some examples:
   * * For single region database instance configs, specify a single regional
   * location KMS key.
   * * For multi-regional database instance configs of type GOOGLE_MANAGED,
   * either specify a multi-regional location KMS key or multiple regional
   * location KMS keys that cover all regions in the instance config.
   * * For a database instance config of type USER_MANAGED, please specify only
   * regional location KMS keys to cover each region in the instance config.
   * Multi-regional location KMS keys are not supported for USER_MANAGED
   * instance configs.
   * </pre>
   *
   * <code>repeated string kms_key_names = 3 [(.google.api.resource_reference) = { ... }</code>
   *
   * @return The count of kmsKeyNames.
   */
  int getKmsKeyNamesCount();
  /**
   *
   *
   * <pre>
   * (--
   * TODO(b/240165507) remove visibility check after cloud spanner multi-region
   * cmek launch.
   * --)
   * Specifies the KMS configuration for the one or more keys used to encrypt
   * the database. Values are of the form
   * `projects/&lt;project&gt;/locations/&lt;location&gt;/keyRings/&lt;key_ring&gt;/cryptoKeys/&lt;kms_key_name&gt;`.
   * The keys referenced by kms_key_names must fully cover all
   * regions of the database instance configuration. Some examples:
   * * For single region database instance configs, specify a single regional
   * location KMS key.
   * * For multi-regional database instance configs of type GOOGLE_MANAGED,
   * either specify a multi-regional location KMS key or multiple regional
   * location KMS keys that cover all regions in the instance config.
   * * For a database instance config of type USER_MANAGED, please specify only
   * regional location KMS keys to cover each region in the instance config.
   * Multi-regional location KMS keys are not supported for USER_MANAGED
   * instance configs.
   * </pre>
   *
   * <code>repeated string kms_key_names = 3 [(.google.api.resource_reference) = { ... }</code>
   *
   * @param index The index of the element to return.
   * @return The kmsKeyNames at the given index.
   */
  java.lang.String getKmsKeyNames(int index);
  /**
   *
   *
   * <pre>
   * (--
   * TODO(b/240165507) remove visibility check after cloud spanner multi-region
   * cmek launch.
   * --)
   * Specifies the KMS configuration for the one or more keys used to encrypt
   * the database. Values are of the form
   * `projects/&lt;project&gt;/locations/&lt;location&gt;/keyRings/&lt;key_ring&gt;/cryptoKeys/&lt;kms_key_name&gt;`.
   * The keys referenced by kms_key_names must fully cover all
   * regions of the database instance configuration. Some examples:
   * * For single region database instance configs, specify a single regional
   * location KMS key.
   * * For multi-regional database instance configs of type GOOGLE_MANAGED,
   * either specify a multi-regional location KMS key or multiple regional
   * location KMS keys that cover all regions in the instance config.
   * * For a database instance config of type USER_MANAGED, please specify only
   * regional location KMS keys to cover each region in the instance config.
   * Multi-regional location KMS keys are not supported for USER_MANAGED
   * instance configs.
   * </pre>
   *
   * <code>repeated string kms_key_names = 3 [(.google.api.resource_reference) = { ... }</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the kmsKeyNames at the given index.
   */
  com.google.protobuf.ByteString getKmsKeyNamesBytes(int index);
}
