/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/admin/database/v1/spanner_database_admin.proto

package com.google.spanner.admin.database.v1;

public final class SpannerDatabaseAdminProto {
  private SpannerDatabaseAdminProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_RestoreInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_RestoreInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_Database_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_Database_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_ListDatabasesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_ListDatabasesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_ListDatabasesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_ListDatabasesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_CreateDatabaseRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_CreateDatabaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_CreateDatabaseMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_CreateDatabaseMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_GetDatabaseRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_GetDatabaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_UpdateDatabaseDdlRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_UpdateDatabaseDdlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_UpdateDatabaseDdlMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_UpdateDatabaseDdlMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_DropDatabaseRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_DropDatabaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_GetDatabaseDdlRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_GetDatabaseDdlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_GetDatabaseDdlResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_GetDatabaseDdlResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_ListDatabaseOperationsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_ListDatabaseOperationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_ListDatabaseOperationsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_ListDatabaseOperationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_RestoreDatabaseRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_RestoreDatabaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_RestoreDatabaseMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_RestoreDatabaseMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_database_v1_OptimizeRestoredDatabaseMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_database_v1_OptimizeRestoredDatabaseMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n=google/spanner/admin/database/v1/spann"
          + "er_database_admin.proto\022 google.spanner."
          + "admin.database.v1\032\034google/api/annotation"
          + "s.proto\032\027google/api/client.proto\032\037google"
          + "/api/field_behavior.proto\032\031google/api/re"
          + "source.proto\032\036google/iam/v1/iam_policy.p"
          + "roto\032\032google/iam/v1/policy.proto\032#google"
          + "/longrunning/operations.proto\032\033google/pr"
          + "otobuf/empty.proto\032\037google/protobuf/time"
          + "stamp.proto\032-google/spanner/admin/databa"
          + "se/v1/backup.proto\032-google/spanner/admin"
          + "/database/v1/common.proto\"\253\001\n\013RestoreInf"
          + "o\022H\n\013source_type\030\001 \001(\01623.google.spanner."
          + "admin.database.v1.RestoreSourceType\022C\n\013b"
          + "ackup_info\030\002 \001(\0132,.google.spanner.admin."
          + "database.v1.BackupInfoH\000B\r\n\013source_info\""
          + "\321\004\n\010Database\022\021\n\004name\030\001 \001(\tB\003\340A\002\022D\n\005state"
          + "\030\002 \001(\01620.google.spanner.admin.database.v"
          + "1.Database.StateB\003\340A\003\0224\n\013create_time\030\003 \001"
          + "(\0132\032.google.protobuf.TimestampB\003\340A\003\022H\n\014r"
          + "estore_info\030\004 \001(\0132-.google.spanner.admin"
          + ".database.v1.RestoreInfoB\003\340A\003\022R\n\021encrypt"
          + "ion_config\030\005 \001(\01322.google.spanner.admin."
          + "database.v1.EncryptionConfigB\003\340A\003\022%\n\030ver"
          + "sion_retention_period\030\006 \001(\tB\003\340A\003\022>\n\025earl"
          + "iest_version_time\030\007 \001(\0132\032.google.protobu"
          + "f.TimestampB\003\340A\003\"M\n\005State\022\025\n\021STATE_UNSPE"
          + "CIFIED\020\000\022\014\n\010CREATING\020\001\022\t\n\005READY\020\002\022\024\n\020REA"
          + "DY_OPTIMIZING\020\003:b\352A_\n\037spanner.googleapis"
          + ".com/Database\022<projects/{project}/instan"
          + "ces/{instance}/databases/{database}\"v\n\024L"
          + "istDatabasesRequest\0227\n\006parent\030\001 \001(\tB\'\340A\002"
          + "\372A!\n\037spanner.googleapis.com/Instance\022\021\n\t"
          + "page_size\030\003 \001(\005\022\022\n\npage_token\030\004 \001(\t\"o\n\025L"
          + "istDatabasesResponse\022=\n\tdatabases\030\001 \003(\0132"
          + "*.google.spanner.admin.database.v1.Datab"
          + "ase\022\027\n\017next_page_token\030\002 \001(\t\"\342\001\n\025CreateD"
          + "atabaseRequest\0227\n\006parent\030\001 \001(\tB\'\340A\002\372A!\n\037"
          + "spanner.googleapis.com/Instance\022\035\n\020creat"
          + "e_statement\030\002 \001(\tB\003\340A\002\022\035\n\020extra_statemen"
          + "ts\030\003 \003(\tB\003\340A\001\022R\n\021encryption_config\030\004 \001(\013"
          + "22.google.spanner.admin.database.v1.Encr"
          + "yptionConfigB\003\340A\001\"P\n\026CreateDatabaseMetad"
          + "ata\0226\n\010database\030\001 \001(\tB$\372A!\n\037spanner.goog"
          + "leapis.com/Database\"K\n\022GetDatabaseReques"
          + "t\0225\n\004name\030\001 \001(\tB\'\340A\002\372A!\n\037spanner.googlea"
          + "pis.com/Database\"\204\001\n\030UpdateDatabaseDdlRe"
          + "quest\0229\n\010database\030\001 \001(\tB\'\340A\002\372A!\n\037spanner"
          + ".googleapis.com/Database\022\027\n\nstatements\030\002"
          + " \003(\tB\003\340A\002\022\024\n\014operation_id\030\003 \001(\t\"\236\001\n\031Upda"
          + "teDatabaseDdlMetadata\0226\n\010database\030\001 \001(\tB"
          + "$\372A!\n\037spanner.googleapis.com/Database\022\022\n"
          + "\nstatements\030\002 \003(\t\0225\n\021commit_timestamps\030\003"
          + " \003(\0132\032.google.protobuf.Timestamp\"P\n\023Drop"
          + "DatabaseRequest\0229\n\010database\030\001 \001(\tB\'\340A\002\372A"
          + "!\n\037spanner.googleapis.com/Database\"R\n\025Ge"
          + "tDatabaseDdlRequest\0229\n\010database\030\001 \001(\tB\'\340"
          + "A\002\372A!\n\037spanner.googleapis.com/Database\","
          + "\n\026GetDatabaseDdlResponse\022\022\n\nstatements\030\001"
          + " \003(\t\"\217\001\n\035ListDatabaseOperationsRequest\0227"
          + "\n\006parent\030\001 \001(\tB\'\340A\002\372A!\n\037spanner.googleap"
          + "is.com/Instance\022\016\n\006filter\030\002 \001(\t\022\021\n\tpage_"
          + "size\030\003 \001(\005\022\022\n\npage_token\030\004 \001(\t\"l\n\036ListDa"
          + "tabaseOperationsResponse\0221\n\noperations\030\001"
          + " \003(\0132\035.google.longrunning.Operation\022\027\n\017n"
          + "ext_page_token\030\002 \001(\t\"\253\001\n\026RestoreDatabase"
          + "Request\0227\n\006parent\030\001 \001(\tB\'\340A\002\372A!\n\037spanner"
          + ".googleapis.com/Instance\022\030\n\013database_id\030"
          + "\002 \001(\tB\003\340A\002\0224\n\006backup\030\003 \001(\tB\"\372A\037\n\035spanner"
          + ".googleapis.com/BackupH\000B\010\n\006source\"\347\002\n\027R"
          + "estoreDatabaseMetadata\022\014\n\004name\030\001 \001(\t\022H\n\013"
          + "source_type\030\002 \001(\01623.google.spanner.admin"
          + ".database.v1.RestoreSourceType\022C\n\013backup"
          + "_info\030\003 \001(\0132,.google.spanner.admin.datab"
          + "ase.v1.BackupInfoH\000\022E\n\010progress\030\004 \001(\01323."
          + "google.spanner.admin.database.v1.Operati"
          + "onProgress\022/\n\013cancel_time\030\005 \001(\0132\032.google"
          + ".protobuf.Timestamp\022(\n optimize_database"
          + "_operation_name\030\006 \001(\tB\r\n\013source_info\"w\n "
          + "OptimizeRestoredDatabaseMetadata\022\014\n\004name"
          + "\030\001 \001(\t\022E\n\010progress\030\002 \001(\01323.google.spanne"
          + "r.admin.database.v1.OperationProgress*5\n"
          + "\021RestoreSourceType\022\024\n\020TYPE_UNSPECIFIED\020\000"
          + "\022\n\n\006BACKUP\020\0012\223\037\n\rDatabaseAdmin\022\300\001\n\rListD"
          + "atabases\0226.google.spanner.admin.database"
          + ".v1.ListDatabasesRequest\0327.google.spanne"
          + "r.admin.database.v1.ListDatabasesRespons"
          + "e\">\202\323\344\223\002/\022-/v1/{parent=projects/*/instan"
          + "ces/*}/databases\332A\006parent\022\244\002\n\016CreateData"
          + "base\0227.google.spanner.admin.database.v1."
          + "CreateDatabaseRequest\032\035.google.longrunni"
          + "ng.Operation\"\271\001\202\323\344\223\0022\"-/v1/{parent=proje"
          + "cts/*/instances/*}/databases:\001*\332A\027parent"
          + ",create_statement\312Ad\n)google.spanner.adm"
          + "in.database.v1.Database\0227google.spanner."
          + "admin.database.v1.CreateDatabaseMetadata"
          + "\022\255\001\n\013GetDatabase\0224.google.spanner.admin."
          + "database.v1.GetDatabaseRequest\032*.google."
          + "spanner.admin.database.v1.Database\"<\202\323\344\223"
          + "\002/\022-/v1/{name=projects/*/instances/*/dat"
          + "abases/*}\332A\004name\022\235\002\n\021UpdateDatabaseDdl\022:"
          + ".google.spanner.admin.database.v1.Update"
          + "DatabaseDdlRequest\032\035.google.longrunning."
          + "Operation\"\254\001\202\323\344\223\002:25/v1/{database=projec"
          + "ts/*/instances/*/databases/*}/ddl:\001*\332A\023d"
          + "atabase,statements\312AS\n\025google.protobuf.E"
          + "mpty\022:google.spanner.admin.database.v1.U"
          + "pdateDatabaseDdlMetadata\022\243\001\n\014DropDatabas"
          + "e\0225.google.spanner.admin.database.v1.Dro"
          + "pDatabaseRequest\032\026.google.protobuf.Empty"
          + "\"D\202\323\344\223\0023*1/v1/{database=projects/*/insta"
          + "nces/*/databases/*}\332A\010database\022\315\001\n\016GetDa"
          + "tabaseDdl\0227.google.spanner.admin.databas"
          + "e.v1.GetDatabaseDdlRequest\0328.google.span"
          + "ner.admin.database.v1.GetDatabaseDdlResp"
          + "onse\"H\202\323\344\223\0027\0225/v1/{database=projects/*/i"
          + "nstances/*/databases/*}/ddl\332A\010database\022\353"
          + "\001\n\014SetIamPolicy\022\".google.iam.v1.SetIamPo"
          + "licyRequest\032\025.google.iam.v1.Policy\"\237\001\202\323\344"
          + "\223\002\206\001\">/v1/{resource=projects/*/instances"
          + "/*/databases/*}:setIamPolicy:\001*ZA\"</v1/{"
          + "resource=projects/*/instances/*/backups/"
          + "*}:setIamPolicy:\001*\332A\017resource,policy\022\344\001\n"
          + "\014GetIamPolicy\022\".google.iam.v1.GetIamPoli"
          + "cyRequest\032\025.google.iam.v1.Policy\"\230\001\202\323\344\223\002"
          + "\206\001\">/v1/{resource=projects/*/instances/*"
          + "/databases/*}:getIamPolicy:\001*ZA\"</v1/{re"
          + "source=projects/*/instances/*/backups/*}"
          + ":getIamPolicy:\001*\332A\010resource\022\234\002\n\022TestIamP"
          + "ermissions\022(.google.iam.v1.TestIamPermis"
          + "sionsRequest\032).google.iam.v1.TestIamPerm"
          + "issionsResponse\"\260\001\202\323\344\223\002\222\001\"D/v1/{resource"
          + "=projects/*/instances/*/databases/*}:tes"
          + "tIamPermissions:\001*ZG\"B/v1/{resource=proj"
          + "ects/*/instances/*/backups/*}:testIamPer"
          + "missions:\001*\332A\024resource,permissions\022\237\002\n\014C"
          + "reateBackup\0225.google.spanner.admin.datab"
          + "ase.v1.CreateBackupRequest\032\035.google.long"
          + "running.Operation\"\270\001\202\323\344\223\0025\"+/v1/{parent="
          + "projects/*/instances/*}/backups:\006backup\332"
          + "A\027parent,backup,backup_id\312A`\n\'google.spa"
          + "nner.admin.database.v1.Backup\0225google.sp"
          + "anner.admin.database.v1.CreateBackupMeta"
          + "data\022\245\001\n\tGetBackup\0222.google.spanner.admi"
          + "n.database.v1.GetBackupRequest\032(.google."
          + "spanner.admin.database.v1.Backup\":\202\323\344\223\002-"
          + "\022+/v1/{name=projects/*/instances/*/backu"
          + "ps/*}\332A\004name\022\310\001\n\014UpdateBackup\0225.google.s"
          + "panner.admin.database.v1.UpdateBackupReq"
          + "uest\032(.google.spanner.admin.database.v1."
          + "Backup\"W\202\323\344\223\002<22/v1/{backup.name=project"
          + "s/*/instances/*/backups/*}:\006backup\332A\022bac"
          + "kup,update_mask\022\231\001\n\014DeleteBackup\0225.googl"
          + "e.spanner.admin.database.v1.DeleteBackup"
          + "Request\032\026.google.protobuf.Empty\":\202\323\344\223\002-*"
          + "+/v1/{name=projects/*/instances/*/backup"
          + "s/*}\332A\004name\022\270\001\n\013ListBackups\0224.google.spa"
          + "nner.admin.database.v1.ListBackupsReques"
          + "t\0325.google.spanner.admin.database.v1.Lis"
          + "tBackupsResponse\"<\202\323\344\223\002-\022+/v1/{parent=pr"
          + "ojects/*/instances/*}/backups\332A\006parent\022\261"
          + "\002\n\017RestoreDatabase\0228.google.spanner.admi"
          + "n.database.v1.RestoreDatabaseRequest\032\035.g"
          + "oogle.longrunning.Operation\"\304\001\202\323\344\223\002:\"5/v"
          + "1/{parent=projects/*/instances/*}/databa"
          + "ses:restore:\001*\332A\031parent,database_id,back"
          + "up\312Ae\n)google.spanner.admin.database.v1."
          + "Database\0228google.spanner.admin.database."
          + "v1.RestoreDatabaseMetadata\022\344\001\n\026ListDatab"
          + "aseOperations\022?.google.spanner.admin.dat"
          + "abase.v1.ListDatabaseOperationsRequest\032@"
          + ".google.spanner.admin.database.v1.ListDa"
          + "tabaseOperationsResponse\"G\202\323\344\223\0028\0226/v1/{p"
          + "arent=projects/*/instances/*}/databaseOp"
          + "erations\332A\006parent\022\334\001\n\024ListBackupOperatio"
          + "ns\022=.google.spanner.admin.database.v1.Li"
          + "stBackupOperationsRequest\032>.google.spann"
          + "er.admin.database.v1.ListBackupOperation"
          + "sResponse\"E\202\323\344\223\0026\0224/v1/{parent=projects/"
          + "*/instances/*}/backupOperations\332A\006parent"
          + "\032x\312A\026spanner.googleapis.com\322A\\https://ww"
          + "w.googleapis.com/auth/cloud-platform,htt"
          + "ps://www.googleapis.com/auth/spanner.adm"
          + "inB\332\002\n$com.google.spanner.admin.database"
          + ".v1B\031SpannerDatabaseAdminProtoP\001ZHgoogle"
          + ".golang.org/genproto/googleapis/spanner/"
          + "admin/database/v1;database\252\002&Google.Clou"
          + "d.Spanner.Admin.Database.V1\312\002&Google\\Clo"
          + "ud\\Spanner\\Admin\\Database\\V1\352\002+Google::C"
          + "loud::Spanner::Admin::Database::V1\352AJ\n\037s"
          + "panner.googleapis.com/Instance\022\'projects"
          + "/{project}/instances/{instance}b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.iam.v1.IamPolicyProto.getDescriptor(),
              com.google.iam.v1.PolicyProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.EmptyProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.spanner.admin.database.v1.BackupProto.getDescriptor(),
              com.google.spanner.admin.database.v1.CommonProto.getDescriptor(),
            });
    internal_static_google_spanner_admin_database_v1_RestoreInfo_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_spanner_admin_database_v1_RestoreInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_RestoreInfo_descriptor,
            new java.lang.String[] {
              "SourceType", "BackupInfo", "SourceInfo",
            });
    internal_static_google_spanner_admin_database_v1_Database_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_spanner_admin_database_v1_Database_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_Database_descriptor,
            new java.lang.String[] {
              "Name",
              "State",
              "CreateTime",
              "RestoreInfo",
              "EncryptionConfig",
              "VersionRetentionPeriod",
              "EarliestVersionTime",
            });
    internal_static_google_spanner_admin_database_v1_ListDatabasesRequest_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_spanner_admin_database_v1_ListDatabasesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_ListDatabasesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken",
            });
    internal_static_google_spanner_admin_database_v1_ListDatabasesResponse_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_spanner_admin_database_v1_ListDatabasesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_ListDatabasesResponse_descriptor,
            new java.lang.String[] {
              "Databases", "NextPageToken",
            });
    internal_static_google_spanner_admin_database_v1_CreateDatabaseRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_spanner_admin_database_v1_CreateDatabaseRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_CreateDatabaseRequest_descriptor,
            new java.lang.String[] {
              "Parent", "CreateStatement", "ExtraStatements", "EncryptionConfig",
            });
    internal_static_google_spanner_admin_database_v1_CreateDatabaseMetadata_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_spanner_admin_database_v1_CreateDatabaseMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_CreateDatabaseMetadata_descriptor,
            new java.lang.String[] {
              "Database",
            });
    internal_static_google_spanner_admin_database_v1_GetDatabaseRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_spanner_admin_database_v1_GetDatabaseRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_GetDatabaseRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_spanner_admin_database_v1_UpdateDatabaseDdlRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_spanner_admin_database_v1_UpdateDatabaseDdlRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_UpdateDatabaseDdlRequest_descriptor,
            new java.lang.String[] {
              "Database", "Statements", "OperationId",
            });
    internal_static_google_spanner_admin_database_v1_UpdateDatabaseDdlMetadata_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_spanner_admin_database_v1_UpdateDatabaseDdlMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_UpdateDatabaseDdlMetadata_descriptor,
            new java.lang.String[] {
              "Database", "Statements", "CommitTimestamps",
            });
    internal_static_google_spanner_admin_database_v1_DropDatabaseRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_spanner_admin_database_v1_DropDatabaseRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_DropDatabaseRequest_descriptor,
            new java.lang.String[] {
              "Database",
            });
    internal_static_google_spanner_admin_database_v1_GetDatabaseDdlRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_spanner_admin_database_v1_GetDatabaseDdlRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_GetDatabaseDdlRequest_descriptor,
            new java.lang.String[] {
              "Database",
            });
    internal_static_google_spanner_admin_database_v1_GetDatabaseDdlResponse_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_spanner_admin_database_v1_GetDatabaseDdlResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_GetDatabaseDdlResponse_descriptor,
            new java.lang.String[] {
              "Statements",
            });
    internal_static_google_spanner_admin_database_v1_ListDatabaseOperationsRequest_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_spanner_admin_database_v1_ListDatabaseOperationsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_ListDatabaseOperationsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Filter", "PageSize", "PageToken",
            });
    internal_static_google_spanner_admin_database_v1_ListDatabaseOperationsResponse_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_spanner_admin_database_v1_ListDatabaseOperationsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_ListDatabaseOperationsResponse_descriptor,
            new java.lang.String[] {
              "Operations", "NextPageToken",
            });
    internal_static_google_spanner_admin_database_v1_RestoreDatabaseRequest_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_spanner_admin_database_v1_RestoreDatabaseRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_RestoreDatabaseRequest_descriptor,
            new java.lang.String[] {
              "Parent", "DatabaseId", "Backup", "Source",
            });
    internal_static_google_spanner_admin_database_v1_RestoreDatabaseMetadata_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_spanner_admin_database_v1_RestoreDatabaseMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_RestoreDatabaseMetadata_descriptor,
            new java.lang.String[] {
              "Name",
              "SourceType",
              "BackupInfo",
              "Progress",
              "CancelTime",
              "OptimizeDatabaseOperationName",
              "SourceInfo",
            });
    internal_static_google_spanner_admin_database_v1_OptimizeRestoredDatabaseMetadata_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_spanner_admin_database_v1_OptimizeRestoredDatabaseMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_database_v1_OptimizeRestoredDatabaseMetadata_descriptor,
            new java.lang.String[] {
              "Name", "Progress",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceDefinition);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.iam.v1.IamPolicyProto.getDescriptor();
    com.google.iam.v1.PolicyProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.spanner.admin.database.v1.BackupProto.getDescriptor();
    com.google.spanner.admin.database.v1.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
