/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/executor/v1/executor.proto

package com.google.spanner.executor.v1;

public final class ExecutorProto {
  private ExecutorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_SpannerAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_SpannerAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_ReadAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_ReadAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_KeyRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_KeyRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_KeySet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_KeySet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_ValueList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_ValueList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_MutationAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_MutationAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_MutationAction_InsertArgs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_MutationAction_InsertArgs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_MutationAction_UpdateArgs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_MutationAction_UpdateArgs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_MutationAction_Mod_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_MutationAction_Mod_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_StartTransactionAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_StartTransactionAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_Concurrency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_Concurrency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_TableMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_TableMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_ColumnMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_ColumnMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_FinishTransactionAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_FinishTransactionAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_AdminAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_AdminAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_CreateUserInstanceConfigAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_CreateUserInstanceConfigAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_UpdateUserInstanceConfigAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_UpdateUserInstanceConfigAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_UpdateUserInstanceConfigAction_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_UpdateUserInstanceConfigAction_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_GetCloudInstanceConfigAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_GetCloudInstanceConfigAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_ListCloudInstanceConfigsAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_ListCloudInstanceConfigsAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_DeleteUserInstanceConfigAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_DeleteUserInstanceConfigAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_CreateCloudInstanceAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_CreateCloudInstanceAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_CreateCloudInstanceAction_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_CreateCloudInstanceAction_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_UpdateCloudInstanceAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_UpdateCloudInstanceAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_UpdateCloudInstanceAction_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_UpdateCloudInstanceAction_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_DeleteCloudInstanceAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_DeleteCloudInstanceAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_CreateCloudDatabaseAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_CreateCloudDatabaseAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_UpdateCloudDatabaseDdlAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_UpdateCloudDatabaseDdlAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_DropCloudDatabaseAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_DropCloudDatabaseAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_ListCloudDatabasesAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_ListCloudDatabasesAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_ListCloudInstancesAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_ListCloudInstancesAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_GetCloudInstanceAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_GetCloudInstanceAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_ListCloudDatabaseOperationsAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_ListCloudDatabaseOperationsAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_RestoreCloudDatabaseAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_RestoreCloudDatabaseAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_GetCloudDatabaseAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_GetCloudDatabaseAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_UpdateInfraDatabaseAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_UpdateInfraDatabaseAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_CreateCloudBackupAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_CreateCloudBackupAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_CopyCloudBackupAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_CopyCloudBackupAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_GetCloudBackupAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_GetCloudBackupAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_UpdateCloudBackupAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_UpdateCloudBackupAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_DeleteCloudBackupAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_DeleteCloudBackupAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_ListCloudBackupsAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_ListCloudBackupsAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_ListCloudBackupOperationsAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_ListCloudBackupOperationsAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_GetOperationAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_GetOperationAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_CancelOperationAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_CancelOperationAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_SpannerActionOutcome_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_SpannerActionOutcome_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_AdminResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_AdminResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_CloudBackupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_CloudBackupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_OperationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_OperationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_CloudInstanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_CloudInstanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_CloudInstanceConfigResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_CloudInstanceConfigResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_CloudDatabaseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_CloudDatabaseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_spanner_executor_v1_ReadResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_executor_v1_ReadResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)google/spanner/executor/v1/executor.pr" +
      "oto\022\032google.spanner.executor.v1\032#google/" +
      "longrunning/operations.proto\032-google/spa" +
      "nner/admin/database/v1/backup.proto\032-goo" +
      "gle/spanner/admin/database/v1/common.pro" +
      "to\032=google/spanner/admin/database/v1/spa" +
      "nner_database_admin.proto\032=google/spanne" +
      "r/admin/instance/v1/spanner_instance_adm" +
      "in.proto\032\037google/protobuf/timestamp.prot" +
      "o\032\034google/spanner/v1/type.proto\032\027google/" +
      "rpc/status.proto\"\356\002\n\rSpannerAction\022\025\n\rda" +
      "tabase_path\030\001 \001(\t\022C\n\005start\030\n \001(\01322.googl" +
      "e.spanner.executor.v1.StartTransactionAc" +
      "tionH\000\022E\n\006finish\030\013 \001(\01323.google.spanner." +
      "executor.v1.FinishTransactionActionH\000\0226\n" +
      "\004read\030\024 \001(\0132&.google.spanner.executor.v1" +
      ".ReadActionH\000\022>\n\010mutation\030\026 \001(\0132*.google" +
      ".spanner.executor.v1.MutationActionH\000\0228\n" +
      "\005admin\030\027 \001(\0132\'.google.spanner.executor.v" +
      "1.AdminActionH\000B\010\n\006action\"\270\001\n\nReadAction" +
      "\022\r\n\005table\030\001 \001(\t\022\022\n\005index\030\002 \001(\tH\000\210\001\001\022\016\n\006c" +
      "olumn\030\003 \003(\t\0220\n\004keys\030\004 \001(\0132\".google.spann" +
      "er.executor.v1.KeySet\022\r\n\005limit\030\005 \001(\005\022\035\n\025" +
      "read_staleness_micros\030\010 \001(\003\022\r\n\005async\030\007 \001" +
      "(\010B\010\n\006_index\"\345\002\n\005Value\022\016\n\004null\030\001 \001(\010H\000\022\023" +
      "\n\tint_value\030\002 \001(\003H\000\022\024\n\nbool_value\030\003 \001(\010H" +
      "\000\022\026\n\014double_value\030\004 \001(\001H\000\022\025\n\013bytes_value" +
      "\030\005 \001(\014H\000\022=\n\014struct_value\030\006 \001(\0132%.google." +
      "spanner.executor.v1.ValueListH\000\0225\n\017times" +
      "tamp_value\030\007 \001(\0132\032.google.protobuf.Times" +
      "tampH\000\022\024\n\ndate_value\030\016 \001(\005H\000\022\032\n\020commit_t" +
      "imestamp\030\017 \001(\010H\000\022<\n\013array_value\030\020 \001(\0132%." +
      "google.spanner.executor.v1.ValueListH\000B\014" +
      "\n\nvalue_type\"\211\002\n\010KeyRange\0224\n\005start\030\001 \001(\013" +
      "2%.google.spanner.executor.v1.ValueList\022" +
      "4\n\005limit\030\002 \001(\0132%.google.spanner.executor" +
      ".v1.ValueList\022<\n\004type\030\003 \001(\0162).google.spa" +
      "nner.executor.v1.KeyRange.TypeH\000\210\001\001\"J\n\004T" +
      "ype\022\021\n\rCLOSED_CLOSED\020\000\022\017\n\013CLOSED_OPEN\020\001\022" +
      "\017\n\013OPEN_CLOSED\020\002\022\r\n\tOPEN_OPEN\020\003B\007\n\005_type" +
      "\"\200\001\n\006KeySet\0224\n\005point\030\001 \003(\0132%.google.span" +
      "ner.executor.v1.ValueList\0223\n\005range\030\002 \003(\013" +
      "2$.google.spanner.executor.v1.KeyRange\022\013" +
      "\n\003all\030\003 \001(\010\"=\n\tValueList\0220\n\005value\030\001 \003(\0132" +
      "!.google.spanner.executor.v1.Value\"\267\005\n\016M" +
      "utationAction\022;\n\003mod\030\001 \003(\0132..google.span" +
      "ner.executor.v1.MutationAction.Mod\032z\n\nIn" +
      "sertArgs\022\016\n\006column\030\001 \003(\t\022%\n\004type\030\002 \003(\0132\027" +
      ".google.spanner.v1.Type\0225\n\006values\030\003 \003(\0132" +
      "%.google.spanner.executor.v1.ValueList\032z" +
      "\n\nUpdateArgs\022\016\n\006column\030\001 \003(\t\022%\n\004type\030\002 \003" +
      "(\0132\027.google.spanner.v1.Type\0225\n\006values\030\003 " +
      "\003(\0132%.google.spanner.executor.v1.ValueLi" +
      "st\032\357\002\n\003Mod\022\r\n\005table\030\001 \001(\t\022E\n\006insert\030\002 \001(" +
      "\01325.google.spanner.executor.v1.MutationA" +
      "ction.InsertArgs\022E\n\006update\030\003 \001(\01325.googl" +
      "e.spanner.executor.v1.MutationAction.Upd" +
      "ateArgs\022O\n\020insert_or_update\030\004 \001(\01325.goog" +
      "le.spanner.executor.v1.MutationAction.In" +
      "sertArgs\022F\n\007replace\030\005 \001(\01325.google.spann" +
      "er.executor.v1.MutationAction.InsertArgs" +
      "\0222\n\006delete\030\006 \001(\0132\".google.spanner.execut" +
      "or.v1.KeySet\"\260\001\n\026StartTransactionAction\022" +
      "<\n\013concurrency\030\002 \001(\0132\'.google.spanner.ex" +
      "ecutor.v1.Concurrency\0228\n\005table\030\003 \003(\0132).g" +
      "oogle.spanner.executor.v1.TableMetadata\022" +
      "\030\n\020transaction_seed\030\006 \001(\tJ\004\010\004\020\006\"\247\002\n\013Conc" +
      "urrency\022\033\n\021staleness_seconds\030\001 \001(\001H\000\022#\n\031" +
      "min_read_timestamp_micros\030\002 \001(\003H\000\022\037\n\025max" +
      "_staleness_seconds\030\003 \001(\001H\000\022 \n\026exact_time" +
      "stamp_micros\030\004 \001(\003H\000\022\020\n\006strong\030\005 \001(\010H\000\022\017" +
      "\n\005batch\030\006 \001(\010H\000\022\033\n\023snapshot_epoch_read\030\007" +
      " \001(\010\022!\n\031snapshot_epoch_root_table\030\010 \001(\t\022" +
      "\034\n\024batch_read_timestamp\030\t \001(\003B\022\n\020concurr" +
      "ency_mode\"\231\001\n\rTableMetadata\022\014\n\004name\030\001 \001(" +
      "\t\022:\n\006column\030\002 \003(\0132*.google.spanner.execu" +
      "tor.v1.ColumnMetadata\022>\n\nkey_column\030\003 \003(" +
      "\0132*.google.spanner.executor.v1.ColumnMet" +
      "adata\"E\n\016ColumnMetadata\022\014\n\004name\030\001 \001(\t\022%\n" +
      "\004type\030\002 \001(\0132\027.google.spanner.v1.Type\"\202\001\n" +
      "\027FinishTransactionAction\022F\n\004mode\030\001 \001(\01628" +
      ".google.spanner.executor.v1.FinishTransa" +
      "ctionAction.Mode\"\037\n\004Mode\022\n\n\006COMMIT\020\000\022\013\n\007" +
      "ABANDON\020\001\"\213\022\n\013AdminAction\022a\n\033create_user" +
      "_instance_config\030$ \001(\0132:.google.spanner." +
      "executor.v1.CreateUserInstanceConfigActi" +
      "onH\000\022a\n\033update_user_instance_config\030\' \001(" +
      "\0132:.google.spanner.executor.v1.UpdateUse" +
      "rInstanceConfigActionH\000\022a\n\033delete_user_i" +
      "nstance_config\030% \001(\0132:.google.spanner.ex" +
      "ecutor.v1.DeleteUserInstanceConfigAction" +
      "H\000\022]\n\031get_cloud_instance_config\030( \001(\01328." +
      "google.spanner.executor.v1.GetCloudInsta" +
      "nceConfigActionH\000\022[\n\025list_instance_confi" +
      "gs\030& \001(\0132:.google.spanner.executor.v1.Li" +
      "stCloudInstanceConfigsActionH\000\022V\n\025create" +
      "_cloud_instance\030\n \001(\01325.google.spanner.e" +
      "xecutor.v1.CreateCloudInstanceActionH\000\022V" +
      "\n\025update_cloud_instance\030\022 \001(\01325.google.s" +
      "panner.executor.v1.UpdateCloudInstanceAc" +
      "tionH\000\022V\n\025delete_cloud_instance\030\" \001(\01325." +
      "google.spanner.executor.v1.DeleteCloudIn" +
      "stanceActionH\000\022T\n\024list_cloud_instances\030\023" +
      " \001(\01324.google.spanner.executor.v1.ListCl" +
      "oudInstancesActionH\000\022P\n\022get_cloud_instan" +
      "ce\030) \001(\01322.google.spanner.executor.v1.Ge" +
      "tCloudInstanceActionH\000\022V\n\025create_cloud_d" +
      "atabase\030\013 \001(\01325.google.spanner.executor." +
      "v1.CreateCloudDatabaseActionH\000\022]\n\031update" +
      "_cloud_database_ddl\030\014 \001(\01328.google.spann" +
      "er.executor.v1.UpdateCloudDatabaseDdlAct" +
      "ionH\000\022R\n\023drop_cloud_database\030\r \001(\01323.goo" +
      "gle.spanner.executor.v1.DropCloudDatabas" +
      "eActionH\000\022T\n\024list_cloud_databases\030\016 \001(\0132" +
      "4.google.spanner.executor.v1.ListCloudDa" +
      "tabasesActionH\000\022g\n\036list_cloud_database_o" +
      "perations\030\017 \001(\0132=.google.spanner.executo" +
      "r.v1.ListCloudDatabaseOperationsActionH\000" +
      "\022X\n\026restore_cloud_database\030\020 \001(\01326.googl" +
      "e.spanner.executor.v1.RestoreCloudDataba" +
      "seActionH\000\022P\n\022get_cloud_database\030\021 \001(\01322" +
      ".google.spanner.executor.v1.GetCloudData" +
      "baseActionH\000\022R\n\023create_cloud_backup\030\024 \001(" +
      "\01323.google.spanner.executor.v1.CreateClo" +
      "udBackupActionH\000\022N\n\021copy_cloud_backup\030# " +
      "\001(\01321.google.spanner.executor.v1.CopyClo" +
      "udBackupActionH\000\022L\n\020get_cloud_backup\030\025 \001" +
      "(\01320.google.spanner.executor.v1.GetCloud" +
      "BackupActionH\000\022R\n\023update_cloud_backup\030\026 " +
      "\001(\01323.google.spanner.executor.v1.UpdateC" +
      "loudBackupActionH\000\022R\n\023delete_cloud_backu" +
      "p\030\027 \001(\01323.google.spanner.executor.v1.Del" +
      "eteCloudBackupActionH\000\022P\n\022list_cloud_bac" +
      "kups\030\030 \001(\01322.google.spanner.executor.v1." +
      "ListCloudBackupsActionH\000\022c\n\034list_cloud_b" +
      "ackup_operations\030\031 \001(\0132;.google.spanner." +
      "executor.v1.ListCloudBackupOperationsAct" +
      "ionH\000\022G\n\rget_operation\030\037 \001(\0132..google.sp" +
      "anner.executor.v1.GetOperationActionH\000\022M" +
      "\n\020cancel_operation\030! \001(\01321.google.spanne" +
      "r.executor.v1.CancelOperationActionH\000B\010\n" +
      "\006action\"\245\001\n\036CreateUserInstanceConfigActi" +
      "on\022\026\n\016user_config_id\030\001 \001(\t\022\022\n\nproject_id" +
      "\030\002 \001(\t\022\026\n\016base_config_id\030\003 \001(\t\022?\n\010replic" +
      "as\030\004 \003(\0132-.google.spanner.admin.instance" +
      ".v1.ReplicaInfo\"\377\001\n\036UpdateUserInstanceCo" +
      "nfigAction\022\026\n\016user_config_id\030\001 \001(\t\022\022\n\npr" +
      "oject_id\030\002 \001(\t\022\031\n\014display_name\030\003 \001(\tH\000\210\001" +
      "\001\022V\n\006labels\030\004 \003(\0132F.google.spanner.execu" +
      "tor.v1.UpdateUserInstanceConfigAction.La" +
      "belsEntry\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\t:\0028\001B\017\n\r_display_name\"N\n\034Get" +
      "CloudInstanceConfigAction\022\032\n\022instance_co" +
      "nfig_id\030\001 \001(\t\022\022\n\nproject_id\030\002 \001(\t\"\202\001\n\036Li" +
      "stCloudInstanceConfigsAction\022\022\n\nproject_" +
      "id\030\001 \001(\t\022\026\n\tpage_size\030\002 \001(\005H\000\210\001\001\022\027\n\npage" +
      "_token\030\003 \001(\tH\001\210\001\001B\014\n\n_page_sizeB\r\n\013_page" +
      "_token\"L\n\036DeleteUserInstanceConfigAction" +
      "\022\026\n\016user_config_id\030\001 \001(\t\022\022\n\nproject_id\030\002" +
      " \001(\t\"\276\002\n\031CreateCloudInstanceAction\022\023\n\013in" +
      "stance_id\030\001 \001(\t\022\022\n\nproject_id\030\002 \001(\t\022\032\n\022i" +
      "nstance_config_id\030\003 \001(\t\022\027\n\nnode_count\030\004 " +
      "\001(\005H\000\210\001\001\022\035\n\020processing_units\030\006 \001(\005H\001\210\001\001\022" +
      "Q\n\006labels\030\005 \003(\0132A.google.spanner.executo" +
      "r.v1.CreateCloudInstanceAction.LabelsEnt" +
      "ry\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001B\r\n\013_node_countB\023\n\021_processing_" +
      "units\"\316\002\n\031UpdateCloudInstanceAction\022\023\n\013i" +
      "nstance_id\030\001 \001(\t\022\022\n\nproject_id\030\002 \001(\t\022\031\n\014" +
      "display_name\030\003 \001(\tH\000\210\001\001\022\027\n\nnode_count\030\004 " +
      "\001(\005H\001\210\001\001\022\035\n\020processing_units\030\005 \001(\005H\002\210\001\001\022" +
      "Q\n\006labels\030\006 \003(\0132A.google.spanner.executo" +
      "r.v1.UpdateCloudInstanceAction.LabelsEnt" +
      "ry\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001B\017\n\r_display_nameB\r\n\013_node_coun" +
      "tB\023\n\021_processing_units\"D\n\031DeleteCloudIns" +
      "tanceAction\022\023\n\013instance_id\030\001 \001(\t\022\022\n\nproj" +
      "ect_id\030\002 \001(\t\"\301\001\n\031CreateCloudDatabaseActi" +
      "on\022\023\n\013instance_id\030\001 \001(\t\022\022\n\nproject_id\030\002 " +
      "\001(\t\022\025\n\rdatabase_name\030\003 \001(\t\022\025\n\rsdl_statem" +
      "ent\030\004 \003(\t\022M\n\021encryption_config\030\005 \001(\01322.g" +
      "oogle.spanner.admin.database.v1.Encrypti" +
      "onConfig\"\213\001\n\034UpdateCloudDatabaseDdlActio" +
      "n\022\023\n\013instance_id\030\001 \001(\t\022\022\n\nproject_id\030\002 \001" +
      "(\t\022\025\n\rdatabase_name\030\003 \001(\t\022\025\n\rsdl_stateme" +
      "nt\030\004 \003(\t\022\024\n\014operation_id\030\005 \001(\t\"Y\n\027DropCl" +
      "oudDatabaseAction\022\023\n\013instance_id\030\001 \001(\t\022\022" +
      "\n\nproject_id\030\002 \001(\t\022\025\n\rdatabase_name\030\003 \001(" +
      "\t\"j\n\030ListCloudDatabasesAction\022\022\n\nproject" +
      "_id\030\001 \001(\t\022\023\n\013instance_id\030\002 \001(\t\022\021\n\tpage_s" +
      "ize\030\003 \001(\005\022\022\n\npage_token\030\004 \001(\t\"\234\001\n\030ListCl" +
      "oudInstancesAction\022\022\n\nproject_id\030\001 \001(\t\022\023" +
      "\n\006filter\030\002 \001(\tH\000\210\001\001\022\026\n\tpage_size\030\003 \001(\005H\001" +
      "\210\001\001\022\027\n\npage_token\030\004 \001(\tH\002\210\001\001B\t\n\007_filterB" +
      "\014\n\n_page_sizeB\r\n\013_page_token\"A\n\026GetCloud" +
      "InstanceAction\022\022\n\nproject_id\030\001 \001(\t\022\023\n\013in" +
      "stance_id\030\002 \001(\t\"\203\001\n!ListCloudDatabaseOpe" +
      "rationsAction\022\022\n\nproject_id\030\001 \001(\t\022\023\n\013ins" +
      "tance_id\030\002 \001(\t\022\016\n\006filter\030\003 \001(\t\022\021\n\tpage_s" +
      "ize\030\004 \001(\005\022\022\n\npage_token\030\005 \001(\t\"\224\001\n\032Restor" +
      "eCloudDatabaseAction\022\022\n\nproject_id\030\001 \001(\t" +
      "\022\032\n\022backup_instance_id\030\002 \001(\t\022\021\n\tbackup_i" +
      "d\030\003 \001(\t\022\034\n\024database_instance_id\030\004 \001(\t\022\025\n" +
      "\rdatabase_name\030\005 \001(\t\"X\n\026GetCloudDatabase" +
      "Action\022\022\n\nproject_id\030\001 \001(\t\022\023\n\013instance_i" +
      "d\030\002 \001(\t\022\025\n\rdatabase_name\030\003 \001(\t\"2\n\031Update" +
      "InfraDatabaseAction\022\025\n\rsdl_statement\030\001 \003" +
      "(\t\"\255\001\n\027CreateCloudBackupAction\022\022\n\nprojec" +
      "t_id\030\001 \001(\t\022\023\n\013instance_id\030\002 \001(\t\022\021\n\tbacku" +
      "p_id\030\003 \001(\t\022\025\n\rdatabase_name\030\004 \001(\t\022\023\n\013exp" +
      "ire_time\030\005 \001(\003\022\031\n\014version_time\030\006 \001(\003H\000\210\001" +
      "\001B\017\n\r_version_time\"\177\n\025CopyCloudBackupAct" +
      "ion\022\022\n\nproject_id\030\001 \001(\t\022\023\n\013instance_id\030\002" +
      " \001(\t\022\021\n\tbackup_id\030\003 \001(\t\022\025\n\rsource_backup" +
      "\030\004 \001(\t\022\023\n\013expire_time\030\005 \001(\003\"R\n\024GetCloudB" +
      "ackupAction\022\022\n\nproject_id\030\001 \001(\t\022\023\n\013insta" +
      "nce_id\030\002 \001(\t\022\021\n\tbackup_id\030\003 \001(\t\"j\n\027Updat" +
      "eCloudBackupAction\022\022\n\nproject_id\030\001 \001(\t\022\023" +
      "\n\013instance_id\030\002 \001(\t\022\021\n\tbackup_id\030\003 \001(\t\022\023" +
      "\n\013expire_time\030\004 \001(\003\"U\n\027DeleteCloudBackup" +
      "Action\022\022\n\nproject_id\030\001 \001(\t\022\023\n\013instance_i" +
      "d\030\002 \001(\t\022\021\n\tbackup_id\030\003 \001(\t\"x\n\026ListCloudB" +
      "ackupsAction\022\022\n\nproject_id\030\001 \001(\t\022\023\n\013inst" +
      "ance_id\030\002 \001(\t\022\016\n\006filter\030\003 \001(\t\022\021\n\tpage_si" +
      "ze\030\004 \001(\005\022\022\n\npage_token\030\005 \001(\t\"\201\001\n\037ListClo" +
      "udBackupOperationsAction\022\022\n\nproject_id\030\001" +
      " \001(\t\022\023\n\013instance_id\030\002 \001(\t\022\016\n\006filter\030\003 \001(" +
      "\t\022\021\n\tpage_size\030\004 \001(\005\022\022\n\npage_token\030\005 \001(\t" +
      "\",\n\022GetOperationAction\022\026\n\016operation_name" +
      "\030\001 \001(\t\"/\n\025CancelOperationAction\022\026\n\016opera" +
      "tion_name\030\001 \001(\t\"\350\001\n\024SpannerActionOutcome" +
      "\022\"\n\006status\030\001 \001(\0132\022.google.rpc.Status\022\021\n\t" +
      "timestamp\030\002 \001(\003\022;\n\013read_result\030\003 \001(\0132&.g" +
      "oogle.spanner.executor.v1.ReadResult\022\035\n\025" +
      "transaction_restarted\030\004 \001(\010\022=\n\014admin_res" +
      "ult\030\005 \001(\0132\'.google.spanner.executor.v1.A" +
      "dminResult\"\231\003\n\013AdminResult\022H\n\017backup_res" +
      "ponse\030\001 \001(\0132/.google.spanner.executor.v1" +
      ".CloudBackupResponse\022I\n\022operation_respon" +
      "se\030\002 \001(\0132-.google.spanner.executor.v1.Op" +
      "erationResponse\022L\n\021database_response\030\003 \001" +
      "(\01321.google.spanner.executor.v1.CloudDat" +
      "abaseResponse\022L\n\021instance_response\030\004 \001(\013" +
      "21.google.spanner.executor.v1.CloudInsta" +
      "nceResponse\022Y\n\030instance_config_response\030" +
      "\005 \001(\01327.google.spanner.executor.v1.Cloud" +
      "InstanceConfigResponse\"\351\001\n\023CloudBackupRe" +
      "sponse\0228\n\006backup\030\001 \001(\0132(.google.spanner." +
      "admin.database.v1.Backup\022?\n\rlisted_backu" +
      "p\030\002 \003(\0132(.google.spanner.admin.database." +
      "v1.Backup\022>\n\027listed_backup_operation\030\003 \003" +
      "(\0132\035.google.longrunning.Operation\022\027\n\017nex" +
      "t_page_token\030\004 \001(\t\"\227\001\n\021OperationResponse" +
      "\0220\n\toperation\030\001 \001(\0132\035.google.longrunning" +
      ".Operation\0227\n\020listed_operation\030\002 \003(\0132\035.g" +
      "oogle.longrunning.Operation\022\027\n\017next_page" +
      "_token\030\003 \001(\t\"\263\001\n\025CloudInstanceResponse\022<" +
      "\n\010instance\030\001 \001(\0132*.google.spanner.admin." +
      "instance.v1.Instance\022C\n\017listed_instance\030" +
      "\002 \003(\0132*.google.spanner.admin.instance.v1" +
      ".Instance\022\027\n\017next_page_token\030\003 \001(\t\"\323\001\n\033C" +
      "loudInstanceConfigResponse\022P\n\026listed_ins" +
      "tance_config\030\001 \003(\01320.google.spanner.admi" +
      "n.instance.v1.InstanceConfig\022\027\n\017next_pag" +
      "e_token\030\002 \001(\t\022I\n\017instance_config\030\003 \001(\01320" +
      ".google.spanner.admin.instance.v1.Instan" +
      "ceConfig\"\365\001\n\025CloudDatabaseResponse\022<\n\010da" +
      "tabase\030\001 \001(\0132*.google.spanner.admin.data" +
      "base.v1.Database\022C\n\017listed_database\030\002 \003(" +
      "\0132*.google.spanner.admin.database.v1.Dat" +
      "abase\022@\n\031listed_database_operation\030\003 \003(\013" +
      "2\035.google.longrunning.Operation\022\027\n\017next_" +
      "page_token\030\004 \001(\t\"\320\001\n\nReadResult\022\r\n\005table" +
      "\030\001 \001(\t\022\020\n\010table_id\030\002 \001(\005\022\r\n\005index\030\003 \001(\t\022" +
      "\025\n\rrequest_index\030\004 \001(\005\0222\n\003row\030\005 \003(\0132%.go" +
      "ogle.spanner.executor.v1.ValueList\022/\n\010ro" +
      "w_type\030\006 \001(\0132\035.google.spanner.v1.StructT" +
      "ype\022\026\n\016read_timestamp\030\007 \001(\003B1\n\036com.googl" +
      "e.spanner.executor.v1B\rExecutorProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.longrunning.OperationsProto.getDescriptor(),
          com.google.spanner.admin.database.v1.BackupProto.getDescriptor(),
          com.google.spanner.admin.database.v1.CommonProto.getDescriptor(),
          com.google.spanner.admin.database.v1.SpannerDatabaseAdminProto.getDescriptor(),
          com.google.spanner.admin.instance.v1.SpannerInstanceAdminProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.spanner.v1.TypeProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
        });
    internal_static_google_spanner_executor_v1_SpannerAction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_spanner_executor_v1_SpannerAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_SpannerAction_descriptor,
        new java.lang.String[] { "DatabasePath", "Start", "Finish", "Read", "Mutation", "Admin", "Action", });
    internal_static_google_spanner_executor_v1_ReadAction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_spanner_executor_v1_ReadAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_ReadAction_descriptor,
        new java.lang.String[] { "Table", "Index", "Column", "Keys", "Limit", "ReadStalenessMicros", "Async", "Index", });
    internal_static_google_spanner_executor_v1_Value_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_spanner_executor_v1_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_Value_descriptor,
        new java.lang.String[] { "Null", "IntValue", "BoolValue", "DoubleValue", "BytesValue", "StructValue", "TimestampValue", "DateValue", "CommitTimestamp", "ArrayValue", "ValueType", });
    internal_static_google_spanner_executor_v1_KeyRange_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_spanner_executor_v1_KeyRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_KeyRange_descriptor,
        new java.lang.String[] { "Start", "Limit", "Type", "Type", });
    internal_static_google_spanner_executor_v1_KeySet_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_spanner_executor_v1_KeySet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_KeySet_descriptor,
        new java.lang.String[] { "Point", "Range", "All", });
    internal_static_google_spanner_executor_v1_ValueList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_spanner_executor_v1_ValueList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_ValueList_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_spanner_executor_v1_MutationAction_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_spanner_executor_v1_MutationAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_MutationAction_descriptor,
        new java.lang.String[] { "Mod", });
    internal_static_google_spanner_executor_v1_MutationAction_InsertArgs_descriptor =
      internal_static_google_spanner_executor_v1_MutationAction_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_executor_v1_MutationAction_InsertArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_MutationAction_InsertArgs_descriptor,
        new java.lang.String[] { "Column", "Type", "Values", });
    internal_static_google_spanner_executor_v1_MutationAction_UpdateArgs_descriptor =
      internal_static_google_spanner_executor_v1_MutationAction_descriptor.getNestedTypes().get(1);
    internal_static_google_spanner_executor_v1_MutationAction_UpdateArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_MutationAction_UpdateArgs_descriptor,
        new java.lang.String[] { "Column", "Type", "Values", });
    internal_static_google_spanner_executor_v1_MutationAction_Mod_descriptor =
      internal_static_google_spanner_executor_v1_MutationAction_descriptor.getNestedTypes().get(2);
    internal_static_google_spanner_executor_v1_MutationAction_Mod_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_MutationAction_Mod_descriptor,
        new java.lang.String[] { "Table", "Insert", "Update", "InsertOrUpdate", "Replace", "Delete", });
    internal_static_google_spanner_executor_v1_StartTransactionAction_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_spanner_executor_v1_StartTransactionAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_StartTransactionAction_descriptor,
        new java.lang.String[] { "Concurrency", "Table", "TransactionSeed", });
    internal_static_google_spanner_executor_v1_Concurrency_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_spanner_executor_v1_Concurrency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_Concurrency_descriptor,
        new java.lang.String[] { "StalenessSeconds", "MinReadTimestampMicros", "MaxStalenessSeconds", "ExactTimestampMicros", "Strong", "Batch", "SnapshotEpochRead", "SnapshotEpochRootTable", "BatchReadTimestamp", "ConcurrencyMode", });
    internal_static_google_spanner_executor_v1_TableMetadata_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_spanner_executor_v1_TableMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_TableMetadata_descriptor,
        new java.lang.String[] { "Name", "Column", "KeyColumn", });
    internal_static_google_spanner_executor_v1_ColumnMetadata_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_spanner_executor_v1_ColumnMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_ColumnMetadata_descriptor,
        new java.lang.String[] { "Name", "Type", });
    internal_static_google_spanner_executor_v1_FinishTransactionAction_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_spanner_executor_v1_FinishTransactionAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_FinishTransactionAction_descriptor,
        new java.lang.String[] { "Mode", });
    internal_static_google_spanner_executor_v1_AdminAction_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_spanner_executor_v1_AdminAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_AdminAction_descriptor,
        new java.lang.String[] { "CreateUserInstanceConfig", "UpdateUserInstanceConfig", "DeleteUserInstanceConfig", "GetCloudInstanceConfig", "ListInstanceConfigs", "CreateCloudInstance", "UpdateCloudInstance", "DeleteCloudInstance", "ListCloudInstances", "GetCloudInstance", "CreateCloudDatabase", "UpdateCloudDatabaseDdl", "DropCloudDatabase", "ListCloudDatabases", "ListCloudDatabaseOperations", "RestoreCloudDatabase", "GetCloudDatabase", "CreateCloudBackup", "CopyCloudBackup", "GetCloudBackup", "UpdateCloudBackup", "DeleteCloudBackup", "ListCloudBackups", "ListCloudBackupOperations", "GetOperation", "CancelOperation", "Action", });
    internal_static_google_spanner_executor_v1_CreateUserInstanceConfigAction_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_spanner_executor_v1_CreateUserInstanceConfigAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_CreateUserInstanceConfigAction_descriptor,
        new java.lang.String[] { "UserConfigId", "ProjectId", "BaseConfigId", "Replicas", });
    internal_static_google_spanner_executor_v1_UpdateUserInstanceConfigAction_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_spanner_executor_v1_UpdateUserInstanceConfigAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_UpdateUserInstanceConfigAction_descriptor,
        new java.lang.String[] { "UserConfigId", "ProjectId", "DisplayName", "Labels", "DisplayName", });
    internal_static_google_spanner_executor_v1_UpdateUserInstanceConfigAction_LabelsEntry_descriptor =
      internal_static_google_spanner_executor_v1_UpdateUserInstanceConfigAction_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_executor_v1_UpdateUserInstanceConfigAction_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_UpdateUserInstanceConfigAction_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_spanner_executor_v1_GetCloudInstanceConfigAction_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_spanner_executor_v1_GetCloudInstanceConfigAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_GetCloudInstanceConfigAction_descriptor,
        new java.lang.String[] { "InstanceConfigId", "ProjectId", });
    internal_static_google_spanner_executor_v1_ListCloudInstanceConfigsAction_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_spanner_executor_v1_ListCloudInstanceConfigsAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_ListCloudInstanceConfigsAction_descriptor,
        new java.lang.String[] { "ProjectId", "PageSize", "PageToken", "PageSize", "PageToken", });
    internal_static_google_spanner_executor_v1_DeleteUserInstanceConfigAction_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_spanner_executor_v1_DeleteUserInstanceConfigAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_DeleteUserInstanceConfigAction_descriptor,
        new java.lang.String[] { "UserConfigId", "ProjectId", });
    internal_static_google_spanner_executor_v1_CreateCloudInstanceAction_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_spanner_executor_v1_CreateCloudInstanceAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_CreateCloudInstanceAction_descriptor,
        new java.lang.String[] { "InstanceId", "ProjectId", "InstanceConfigId", "NodeCount", "ProcessingUnits", "Labels", "NodeCount", "ProcessingUnits", });
    internal_static_google_spanner_executor_v1_CreateCloudInstanceAction_LabelsEntry_descriptor =
      internal_static_google_spanner_executor_v1_CreateCloudInstanceAction_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_executor_v1_CreateCloudInstanceAction_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_CreateCloudInstanceAction_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_spanner_executor_v1_UpdateCloudInstanceAction_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_google_spanner_executor_v1_UpdateCloudInstanceAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_UpdateCloudInstanceAction_descriptor,
        new java.lang.String[] { "InstanceId", "ProjectId", "DisplayName", "NodeCount", "ProcessingUnits", "Labels", "DisplayName", "NodeCount", "ProcessingUnits", });
    internal_static_google_spanner_executor_v1_UpdateCloudInstanceAction_LabelsEntry_descriptor =
      internal_static_google_spanner_executor_v1_UpdateCloudInstanceAction_descriptor.getNestedTypes().get(0);
    internal_static_google_spanner_executor_v1_UpdateCloudInstanceAction_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_UpdateCloudInstanceAction_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_spanner_executor_v1_DeleteCloudInstanceAction_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_google_spanner_executor_v1_DeleteCloudInstanceAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_DeleteCloudInstanceAction_descriptor,
        new java.lang.String[] { "InstanceId", "ProjectId", });
    internal_static_google_spanner_executor_v1_CreateCloudDatabaseAction_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_google_spanner_executor_v1_CreateCloudDatabaseAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_CreateCloudDatabaseAction_descriptor,
        new java.lang.String[] { "InstanceId", "ProjectId", "DatabaseName", "SdlStatement", "EncryptionConfig", });
    internal_static_google_spanner_executor_v1_UpdateCloudDatabaseDdlAction_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_google_spanner_executor_v1_UpdateCloudDatabaseDdlAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_UpdateCloudDatabaseDdlAction_descriptor,
        new java.lang.String[] { "InstanceId", "ProjectId", "DatabaseName", "SdlStatement", "OperationId", });
    internal_static_google_spanner_executor_v1_DropCloudDatabaseAction_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_google_spanner_executor_v1_DropCloudDatabaseAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_DropCloudDatabaseAction_descriptor,
        new java.lang.String[] { "InstanceId", "ProjectId", "DatabaseName", });
    internal_static_google_spanner_executor_v1_ListCloudDatabasesAction_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_google_spanner_executor_v1_ListCloudDatabasesAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_ListCloudDatabasesAction_descriptor,
        new java.lang.String[] { "ProjectId", "InstanceId", "PageSize", "PageToken", });
    internal_static_google_spanner_executor_v1_ListCloudInstancesAction_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_google_spanner_executor_v1_ListCloudInstancesAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_ListCloudInstancesAction_descriptor,
        new java.lang.String[] { "ProjectId", "Filter", "PageSize", "PageToken", "Filter", "PageSize", "PageToken", });
    internal_static_google_spanner_executor_v1_GetCloudInstanceAction_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_google_spanner_executor_v1_GetCloudInstanceAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_GetCloudInstanceAction_descriptor,
        new java.lang.String[] { "ProjectId", "InstanceId", });
    internal_static_google_spanner_executor_v1_ListCloudDatabaseOperationsAction_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_google_spanner_executor_v1_ListCloudDatabaseOperationsAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_ListCloudDatabaseOperationsAction_descriptor,
        new java.lang.String[] { "ProjectId", "InstanceId", "Filter", "PageSize", "PageToken", });
    internal_static_google_spanner_executor_v1_RestoreCloudDatabaseAction_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_google_spanner_executor_v1_RestoreCloudDatabaseAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_RestoreCloudDatabaseAction_descriptor,
        new java.lang.String[] { "ProjectId", "BackupInstanceId", "BackupId", "DatabaseInstanceId", "DatabaseName", });
    internal_static_google_spanner_executor_v1_GetCloudDatabaseAction_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_google_spanner_executor_v1_GetCloudDatabaseAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_GetCloudDatabaseAction_descriptor,
        new java.lang.String[] { "ProjectId", "InstanceId", "DatabaseName", });
    internal_static_google_spanner_executor_v1_UpdateInfraDatabaseAction_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_google_spanner_executor_v1_UpdateInfraDatabaseAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_UpdateInfraDatabaseAction_descriptor,
        new java.lang.String[] { "SdlStatement", });
    internal_static_google_spanner_executor_v1_CreateCloudBackupAction_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_google_spanner_executor_v1_CreateCloudBackupAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_CreateCloudBackupAction_descriptor,
        new java.lang.String[] { "ProjectId", "InstanceId", "BackupId", "DatabaseName", "ExpireTime", "VersionTime", "VersionTime", });
    internal_static_google_spanner_executor_v1_CopyCloudBackupAction_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_google_spanner_executor_v1_CopyCloudBackupAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_CopyCloudBackupAction_descriptor,
        new java.lang.String[] { "ProjectId", "InstanceId", "BackupId", "SourceBackup", "ExpireTime", });
    internal_static_google_spanner_executor_v1_GetCloudBackupAction_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_google_spanner_executor_v1_GetCloudBackupAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_GetCloudBackupAction_descriptor,
        new java.lang.String[] { "ProjectId", "InstanceId", "BackupId", });
    internal_static_google_spanner_executor_v1_UpdateCloudBackupAction_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_google_spanner_executor_v1_UpdateCloudBackupAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_UpdateCloudBackupAction_descriptor,
        new java.lang.String[] { "ProjectId", "InstanceId", "BackupId", "ExpireTime", });
    internal_static_google_spanner_executor_v1_DeleteCloudBackupAction_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_google_spanner_executor_v1_DeleteCloudBackupAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_DeleteCloudBackupAction_descriptor,
        new java.lang.String[] { "ProjectId", "InstanceId", "BackupId", });
    internal_static_google_spanner_executor_v1_ListCloudBackupsAction_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_google_spanner_executor_v1_ListCloudBackupsAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_ListCloudBackupsAction_descriptor,
        new java.lang.String[] { "ProjectId", "InstanceId", "Filter", "PageSize", "PageToken", });
    internal_static_google_spanner_executor_v1_ListCloudBackupOperationsAction_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_google_spanner_executor_v1_ListCloudBackupOperationsAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_ListCloudBackupOperationsAction_descriptor,
        new java.lang.String[] { "ProjectId", "InstanceId", "Filter", "PageSize", "PageToken", });
    internal_static_google_spanner_executor_v1_GetOperationAction_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_google_spanner_executor_v1_GetOperationAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_GetOperationAction_descriptor,
        new java.lang.String[] { "OperationName", });
    internal_static_google_spanner_executor_v1_CancelOperationAction_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_google_spanner_executor_v1_CancelOperationAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_CancelOperationAction_descriptor,
        new java.lang.String[] { "OperationName", });
    internal_static_google_spanner_executor_v1_SpannerActionOutcome_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_google_spanner_executor_v1_SpannerActionOutcome_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_SpannerActionOutcome_descriptor,
        new java.lang.String[] { "Status", "Timestamp", "ReadResult", "TransactionRestarted", "AdminResult", });
    internal_static_google_spanner_executor_v1_AdminResult_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_google_spanner_executor_v1_AdminResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_AdminResult_descriptor,
        new java.lang.String[] { "BackupResponse", "OperationResponse", "DatabaseResponse", "InstanceResponse", "InstanceConfigResponse", });
    internal_static_google_spanner_executor_v1_CloudBackupResponse_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_google_spanner_executor_v1_CloudBackupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_CloudBackupResponse_descriptor,
        new java.lang.String[] { "Backup", "ListedBackup", "ListedBackupOperation", "NextPageToken", });
    internal_static_google_spanner_executor_v1_OperationResponse_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_google_spanner_executor_v1_OperationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_OperationResponse_descriptor,
        new java.lang.String[] { "Operation", "ListedOperation", "NextPageToken", });
    internal_static_google_spanner_executor_v1_CloudInstanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_google_spanner_executor_v1_CloudInstanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_CloudInstanceResponse_descriptor,
        new java.lang.String[] { "Instance", "ListedInstance", "NextPageToken", });
    internal_static_google_spanner_executor_v1_CloudInstanceConfigResponse_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_google_spanner_executor_v1_CloudInstanceConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_CloudInstanceConfigResponse_descriptor,
        new java.lang.String[] { "ListedInstanceConfig", "NextPageToken", "InstanceConfig", });
    internal_static_google_spanner_executor_v1_CloudDatabaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_google_spanner_executor_v1_CloudDatabaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_CloudDatabaseResponse_descriptor,
        new java.lang.String[] { "Database", "ListedDatabase", "ListedDatabaseOperation", "NextPageToken", });
    internal_static_google_spanner_executor_v1_ReadResult_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_google_spanner_executor_v1_ReadResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_spanner_executor_v1_ReadResult_descriptor,
        new java.lang.String[] { "Table", "TableId", "Index", "RequestIndex", "Row", "RowType", "ReadTimestamp", });
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.spanner.admin.database.v1.BackupProto.getDescriptor();
    com.google.spanner.admin.database.v1.CommonProto.getDescriptor();
    com.google.spanner.admin.database.v1.SpannerDatabaseAdminProto.getDescriptor();
    com.google.spanner.admin.instance.v1.SpannerInstanceAdminProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.spanner.v1.TypeProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
