'on':
  push:
    branches:
      - 6.23.x
  pull_request: null
name: ci
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 11
          - 17
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{matrix.java}}
      - run: java -version
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: test
  units-java8:
    name: units (8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
      - run: echo "JAVA8_HOME=${JAVA_HOME}" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - run: echo "JAVA11_HOME=${JAVA_HOME}" >> $GITHUB_ENV
        shell: bash
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: test
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
      - run: echo "JAVA8_HOME=${JAVA_HOME}" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - run: echo "JAVA11_HOME=${JAVA_HOME}" >> $GITHUB_ENV
        shell: bash
      - run: java -version
      - run: .kokoro/build.bat
        env:
          JOB_TYPE: test
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 8
          - 11
          - 17
    steps:
      - uses: actions/checkout@v3
      - if: ${{matrix.java}} == '8'
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - if: ${{matrix.java}} == '8'
        run: echo "JAVA11_HOME=${JAVA_HOME}" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{matrix.java}}
      - if: ${{matrix.java}} == '8'
        run: echo "JAVA8_HOME=${JAVA_HOME}" >> $GITHUB_ENV
        shell: bash
      - run: java -version
      - run: .kokoro/dependencies.sh
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - run: java -version
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: lint
  clirr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - run: java -version
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: clirr
