'on':
  push:
    branches:
      - 6.95.x
  pull_request: null
name: ci
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 11
          - 17
          - 21
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
      - run: java -version
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: test
  units-with-multiplexed-session:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 11
          - 17
          - 21
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
      - run: java -version
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: test
          GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS_PARTITIONED_OPS: true
          GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS_FOR_RW: true
  units-with-regular-session:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 11
          - 17
          - 21
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
      - run: java -version
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: test
          GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS: false
  units-java8:
    name: units (8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - run: echo "SUREFIRE_JVM_OPT=-Djvm=${JAVA_HOME}/bin/java" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: test
  units-with-multiplexed-session8:
    name: units-with-multiplexed-session (8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - run: echo "SUREFIRE_JVM_OPT=-Djvm=${JAVA_HOME}/bin/java" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: test
          GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS: true
          GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS_PARTITIONED_OPS: true
          GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS_FOR_RW: true
  units-with-regular-session8:
    name: units-with-regular-session (8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - run: echo "SUREFIRE_JVM_OPT=-Djvm=${JAVA_HOME}/bin/java" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: test
          GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS: false
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - run: echo "JAVA8_HOME=${JAVA_HOME}" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - run: echo "JAVA11_HOME=${JAVA_HOME}" >> $GITHUB_ENV
        shell: bash
      - run: java -version
      - run: .kokoro/build.bat
        env:
          JOB_TYPE: test
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
      - run: java -version
      - run: .kokoro/dependencies.sh
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: java -version
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: javadoc
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: java -version
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: lint
  clirr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: java -version
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: clirr
